
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Papa Isam
 */
public class Laporan_Depi extends javax.swing.JFrame {

    /**
     * Creates new form Laporan_Depi
     */
    private DefaultTableModel mdl = new DefaultTableModel(){
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
     private DefaultTableModel mdl2 = new DefaultTableModel(){
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    
    public Laporan_Depi() {
        initComponents();
        mdl.addColumn("No.");
        mdl.addColumn("No.Deposit");
        mdl.addColumn("Nama");
        mdl.addColumn("Tanggal");
        mdl.addColumn("Total Deposit");
        mdl.addColumn("Sisa Saldo");
        mdl.addColumn("Total Transaksi");
        mdl.addColumn("Keterangan");
        mdl2.addColumn("No.");
        mdl2.addColumn("No.Piutang");
        mdl2.addColumn("Nama");
        mdl2.addColumn("No. Hp");
        mdl2.addColumn("Tanggal Transaksi");
        mdl2.addColumn("Tanggal Jatuh Tempo");
        mdl2.addColumn("Total Piutang");
        mdl2.addColumn("Sisa Piutang");
        mdl2.addColumn("Keterangan");
        jTable1.setModel(mdl);
        jTable2.setModel(mdl2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        Tampilkan = new javax.swing.JButton();
        Cetak = new javax.swing.JButton();
        bersihkan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lbl_sisadeposit = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        kunci_pende = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        lbl_tottrans = new javax.swing.JLabel();
        Hapus = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        Tampilkan2 = new javax.swing.JButton();
        Cetak2 = new javax.swing.JButton();
        bersihkan2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lbl_totpiutang = new javax.swing.JLabel();
        lbl_sisapiutang = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        kunci_penpi = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        Tampilkan1 = new javax.swing.JButton();
        lbl_penjualanhar3 = new javax.swing.JLabel();
        lbl_penjualanhar4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1350, 700));

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LAPORAN DEPOSIT");

        Tampilkan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Tampilkan.setText("Cari");
        Tampilkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TampilkanActionPerformed(evt);
            }
        });

        Cetak.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Cetak.setText("Cetak Laporan");
        Cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CetakActionPerformed(evt);
            }
        });

        bersihkan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bersihkan.setText("Bersihkan");
        bersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bersihkanActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Total Deposit Tersisa :");

        lbl_sisadeposit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_sisadeposit.setText("Rp 0,00");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel19.setText("Kunci Pencarian");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Semua Deposit", "Saldo Tersisa", "Saldo Habis", "No. Deposit", "Nama Deposit" }));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Total Transaksi         :");

        lbl_tottrans.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_tottrans.setText("Rp 0,00");

        Hapus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Hapus.setText("Hapus Item Terpilih");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(kunci_pende, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Tampilkan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Cetak)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bersihkan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_tottrans, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_sisadeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(10, 10, 10))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(kunci_pende, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tampilkan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lbl_sisadeposit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lbl_tottrans)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cetak)
                            .addComponent(Hapus)
                            .addComponent(bersihkan))))
                .addGap(32, 32, 32))
        );

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LAPORAN DEPOSIT & PIUTANG TB. RIZKY PUTRA");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("LAPORAN PIUTANG");

        Tampilkan2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Tampilkan2.setText("Cetak Laporan");
        Tampilkan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tampilkan2ActionPerformed(evt);
            }
        });

        Cetak2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Cetak2.setText("Hapus Item Terpilih");
        Cetak2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cetak2ActionPerformed(evt);
            }
        });

        bersihkan2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bersihkan2.setText("Bersihkan");
        bersihkan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bersihkan2ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("Total Piutang");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("Sisa Piutang");

        lbl_totpiutang.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_totpiutang.setText("Rp 0,00");

        lbl_sisapiutang.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_sisapiutang.setText("Rp 0,00");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel20.setText("Kunci Pencarian");

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Semua Piutang", "Jatuh Tempo", "Piutang Lunas", "Piutang Belum Lunas", "No. Piutang", "Nama Piutang" }));

        Tampilkan1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Tampilkan1.setText("Cari");
        Tampilkan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tampilkan1ActionPerformed(evt);
            }
        });

        lbl_penjualanhar3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_penjualanhar3.setText(":");

        lbl_penjualanhar4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_penjualanhar4.setText(":");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kunci_penpi, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(Tampilkan1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(Tampilkan2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Cetak2)
                        .addGap(29, 29, 29)
                        .addComponent(bersihkan2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_penjualanhar4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_sisapiutang, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_penjualanhar3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_totpiutang, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(kunci_penpi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tampilkan1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_totpiutang)
                            .addComponent(lbl_penjualanhar3)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_sisapiutang)
                            .addComponent(lbl_penjualanhar4)
                            .addComponent(jLabel16))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tampilkan2)
                            .addComponent(Cetak2)
                            .addComponent(bersihkan2))
                        .addGap(38, 38, 38))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TampilkanActionPerformed
        // TODO add your handling code here:
        bersihkan_Table();
        String pil = jComboBox1.getSelectedItem().toString(),sql="";
        switch (pil) {
            case "Semua Deposit":
                sql="select * from deposit order by tgl";
                pen_dep="semua deposit";
                break;
            case "Saldo Tersisa":
                sql="select * from deposit where saldo!='0' order by tgl";
                pen_dep="deposit saldo tersisa";
                break;
            case "Saldo Habis":
                sql="select * from deposit where saldo='0' order by tgl";
                pen_dep="deposit saldo habis";
                break;
            case "No. Deposit":
                sql="select * from deposit where no_deposit='"+kunci_pende.getText().trim()+"' order by tgl";
                pen_dep="deposit no."+kunci_pende.getText().trim();
                break;
            case "Nama Deposit":
                sql="select * from deposit where nama like'%"+kunci_pende.getText().trim()+"%' order by tgl";
                pen_dep="Nama :"+kunci_pende.getText().trim();
                break;
        }
        int i=1;long tot_sal=0,tot_trans=0;
        try{
             Class.forName(JDBC_DRIVER);
            Connection cn = DriverManager.getConnection(DB_URL,USER,PASS);
            Statement smt = cn.createStatement();
            ResultSet rs = smt.executeQuery(sql);
            while(rs.next()){
                Date date = dt.parse(rs.getString("tgl"));
                String tanggal = dt2.format(date)+" "+rs.getString("jam");
                mdl.addRow(new Object [] {i,rs.getString("No_deposit"),rs.getString("nama"),tanggal,get_totdep(rs.getString("No_deposit"),rs.getString("Jum_deposit")),set_Rp(Long.parseLong(rs.getString("saldo"))),set_Rp(get_totrans(rs.getString("No_deposit"))),get_ket(rs.getString("No_deposit"))});
                tot_sal+=Long.parseLong(rs.getString("saldo"));
                tot_trans+=get_totrans(rs.getString("No_deposit"));
                i++;
            }
            jTable1.setModel(mdl);
            lbl_sisadeposit.setText(set_Rp(tot_sal));
            lbl_tottrans.setText(set_Rp(tot_trans));
        }catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_TampilkanActionPerformed

    private void CetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CetakActionPerformed
        // TODO add your handling code here:
        try{
            HashMap parameter = new HashMap();
            File file = new File("src/Laporan_deposit.jasper");
            parameter.put("jenis_lap",pen_dep);
            parameter.put("tot_dep",lbl_sisadeposit.getText());
            parameter.put("to_trans",lbl_tottrans.getText());
            JasperReport jp = (JasperReport) JRLoader.loadObject(file);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jp,parameter,new JRTableModelDataSource(mdl));
            JasperViewer.viewReport(jasperPrint,false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Data tidak dapat dicetak!"+e.getMessage(),"Informasi",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CetakActionPerformed

    private void bersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bersihkanActionPerformed
        // TODO add your handling code here:
        bersihkan_Table();
        kunci_pende.setText("");
        lbl_sisadeposit.setText("Rp 0,00");
        lbl_tottrans.setText("Rp 0,00");
    }//GEN-LAST:event_bersihkanActionPerformed

    private void Tampilkan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tampilkan2ActionPerformed
        // TODO add your handling code here:
        try{
            HashMap parameter = new HashMap();
            File file = new File("src/Laporan_piutang.jasper");
            parameter.put("jenis_lap",pesan);
            parameter.put("tot_piutang",lbl_totpiutang.getText());
            parameter.put("sisa_piutang",lbl_sisapiutang.getText());
            JasperReport jp = (JasperReport) JRLoader.loadObject(file);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jp,parameter,new JRTableModelDataSource(mdl2));
            JasperViewer.viewReport(jasperPrint,false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Data tidak dapat dicetak!"+e.getMessage(),"Informasi",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Tampilkan2ActionPerformed

    private void Cetak2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cetak2ActionPerformed
        // TODO add your handling code here:
        Date ys = new Date();
        int col = jTable2.getSelectedRow();
        if(col>=0){
            try{
                Class.forName(JDBC_DRIVER);
                Connection cn = DriverManager.getConnection(DB_URL,USER,PASS);
                Statement smt = cn.createStatement();
                String pesan = "Anda yakin akan menghapus Piutang \nNo."+jTable2.getModel().getValueAt(col, 1).toString()+"\nNama :"+jTable2.getModel().getValueAt(col, 2).toString();
                int result = JOptionPane.showConfirmDialog(null,pesan,"Confirmation Message",JOptionPane.YES_NO_OPTION);;
                if(result == JOptionPane.YES_OPTION){
                    if(jTable2.getModel().getValueAt(col,7).toString().equals("Rp 0,00")){
                        int a = smt.executeUpdate("delete from piutang where no_piutang='"+jTable2.getModel().getValueAt(col, 1).toString()+"'");
                        int b = smt.executeUpdate("delete from pembayaran_piutang where no_piutang='"+jTable2.getModel().getValueAt(col, 1).toString()+"'");
                        mdl2.removeRow(col);
                        if(a>0&&b>0){
                            JOptionPane.showMessageDialog(this,"Data berhasil dihapus","Informasi",JOptionPane.INFORMATION_MESSAGE);
                            smt.executeUpdate("insert into log_hapus (Tgl_hapus,Jam_hapus,Data_dihapus) values ('"
                                    +dt.format(ys)+"','"+dt3.format(ys)+"','"+"Hapus data deposit no."
                                    +jTable2.getModel().getValueAt(col, 1).toString()+", Nama :"+jTable2.getModel().getValueAt(col, 2).toString()+"')");
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(this,"Sisa piutang masih ada, data tidak bisa dihapus!","Informasi",JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            }catch (Exception e){
                e.printStackTrace();
                }   
        }
        else{
             JOptionPane.showMessageDialog(this,"Tidak ada item terpilih!","Informasi",JOptionPane.INFORMATION_MESSAGE);   
            }
    }//GEN-LAST:event_Cetak2ActionPerformed

    private void bersihkan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bersihkan2ActionPerformed
        // TODO add your handling code here:
       bersihkan_Table2();
       kunci_penpi.setText("");
       lbl_totpiutang.setText("Rp 0,00");
       lbl_sisapiutang.setText("Rp 0,00");
        
    }//GEN-LAST:event_bersihkan2ActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
        Date ys = new Date();
        int col = jTable1.getSelectedRow();
        if(col>=0){
            try{
                Class.forName(JDBC_DRIVER);
                Connection cn = DriverManager.getConnection(DB_URL,USER,PASS);
                Statement smt = cn.createStatement();
                String pesan = "Anda yakin akan menghapus Deposit \nNo."+jTable1.getModel().getValueAt(col, 1).toString()+"\nNama :"+jTable1.getModel().getValueAt(col, 2).toString();
                int result = JOptionPane.showConfirmDialog(null,pesan,"Confirmation Message",JOptionPane.YES_NO_OPTION);;
                if(result == JOptionPane.YES_OPTION){
                    if(jTable1.getModel().getValueAt(col,5).toString().equals("Rp 0,00")){
                        int a = smt.executeUpdate("delete from deposit where no_deposit='"+jTable1.getModel().getValueAt(col, 1).toString()+"'");
                        int b = smt.executeUpdate("delete from tambah_deposit where no_deposit='"+jTable1.getModel().getValueAt(col, 1).toString()+"'");
                        mdl.removeRow(col);
                        if(a>0&&b>0){
                            JOptionPane.showMessageDialog(this,"Data berhasil dihapus","Informasi",JOptionPane.INFORMATION_MESSAGE);
                            smt.executeUpdate("insert into log_hapus (Tgl_hapus,Jam_hapus,Data_dihapus) values ('"
                                    +dt.format(ys)+"','"+dt3.format(ys)+"','"+"Hapus data deposit no."
                                    +jTable1.getModel().getValueAt(col, 1).toString()+", Nama :"+jTable1.getModel().getValueAt(col, 2).toString()+"')");
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(this,"Sisa saldo deposit masih ada, data tidak bisa dihapus!","Informasi",JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            }catch (Exception e){
                e.printStackTrace();
                }   
        }
        else{
             JOptionPane.showMessageDialog(this,"Tidak ada item terpilih!","Informasi",JOptionPane.INFORMATION_MESSAGE);   
            }
    }//GEN-LAST:event_HapusActionPerformed

    private void Tampilkan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tampilkan1ActionPerformed
        // TODO add your handling code here:
        Date ys = new Date();
        bersihkan_Table2();
        String pil=jComboBox2.getSelectedItem().toString();
        String sql="";
        switch(pil){
            case"Semua Piutang":
                sql="select*from piutang";
                pesan="Semua piutang";
                break;
            case"Jatuh Tempo":
                sql="select*from piutang where Tgl_jatuhtempo<='"+dt.format(ys)+"'";
                pesan="Piutang Jatuh Tempo";
                break;
            case "Piutang Lunas":
                sql="select*from piutang where Sisa_piutang='0'";
                pesan="Piutang Lunas";
                break;
            case "Piutang Belum Lunas":
                sql="select*from piutang where Sisa_piutang>'0'";
                pesan="Piutang Lunas";
                break;
            case "No. Piutang":
                sql="select*from piutang where No_piutang ='"+kunci_penpi.getText().trim()+"'";
                pesan="Piutang No."+kunci_penpi.getText().trim();
                break;
            case "Nama Piutang":
                sql="select*from piutang where Nama like'%"+kunci_penpi.getText().trim()+"%'";
                pesan="Piutang Nama."+kunci_penpi.getText().trim();
                break;
        }
        int i=1;String tgl_tr,tgl_jt;
        long tot_pi=0,piu=0,sisa_piutang=0,tot_piutangsisa=0;
         try{
                Class.forName(JDBC_DRIVER);
                Connection cn = DriverManager.getConnection(DB_URL,USER,PASS);
                Statement smt = cn.createStatement();
                ResultSet rs = smt.executeQuery(sql);
                while(rs.next()){
                    Date tgl=dt.parse(rs.getString("tgl_trans"));
                    tgl_tr=dt2.format(tgl);
                    tgl=dt.parse(rs.getString("Tgl_jatuhtempo"));
                    tgl_jt=dt2.format(tgl);
                    piu=Long.parseLong(rs.getString("Total"));
                    sisa_piutang=Long.parseLong(rs.getString("Sisa_piutang"));
                    mdl2.addRow(new Object[]{i,rs.getString("no_piutang"),rs.getString("nama"),rs.getString("no_hp"),tgl_tr,tgl_jt,set_Rp(piu),set_Rp(sisa_piutang),rs.getString("keterangan")});
                    tot_pi+=piu;
                    tot_piutangsisa+=sisa_piutang;
                    i++;
                }
                jTable2.setModel(mdl2);
                lbl_totpiutang.setText(set_Rp(tot_pi));
                lbl_sisapiutang.setText(set_Rp(tot_piutangsisa));
        }catch (Exception e){
        e.printStackTrace();
           } 
        
        
    }//GEN-LAST:event_Tampilkan1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laporan_Depi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laporan_Depi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laporan_Depi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laporan_Depi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laporan_Depi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cetak;
    private javax.swing.JButton Cetak2;
    private javax.swing.JButton Hapus;
    private javax.swing.JButton Tampilkan;
    private javax.swing.JButton Tampilkan1;
    private javax.swing.JButton Tampilkan2;
    private javax.swing.JButton bersihkan;
    private javax.swing.JButton bersihkan2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField kunci_pende;
    private javax.swing.JTextField kunci_penpi;
    private javax.swing.JLabel lbl_penjualanhar3;
    private javax.swing.JLabel lbl_penjualanhar4;
    private javax.swing.JLabel lbl_sisadeposit;
    private javax.swing.JLabel lbl_sisapiutang;
    private javax.swing.JLabel lbl_totpiutang;
    private javax.swing.JLabel lbl_tottrans;
    // End of variables declaration//GEN-END:variables
    
    static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
    static final String DB_URL = "jdbc:mysql://localhost/TB_RP";
    static final String USER = "root";
    static final String PASS = "";
    SimpleDateFormat dt=new SimpleDateFormat("yyyy-MM-dd");
    SimpleDateFormat dt2=new SimpleDateFormat("dd/MM/yyyy");
    SimpleDateFormat dt3=new SimpleDateFormat("kk:mm:ss");
    String pen_dep="";
    String pesan="";
        
    public String set_Rp(Long bil){
        DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
        DecimalFormatSymbols formatRp = new DecimalFormatSymbols();

        formatRp.setCurrencySymbol("Rp ");
        formatRp.setMonetaryDecimalSeparator(',');
        formatRp.setGroupingSeparator('.');

        kursIndonesia.setDecimalFormatSymbols(formatRp);
        
        return kursIndonesia.format(bil);
    }
    
    public void bersihkan_Table(){
        int j_brs = mdl.getRowCount()-1;
        int i = j_brs;
        while(i>=0){
            mdl.removeRow(i);
            i=i-1;
        }
    }
    
    public void bersihkan_Table2(){
        int j_brs = mdl2.getRowCount()-1;
        int i = j_brs;
        while(i>=0){
            mdl2.removeRow(i);
            i=i-1;
        }
    }

    private String get_totdep(String no_dep,String sal_awal) {
        long total = Long.parseLong(sal_awal);
        try{
             Class.forName(JDBC_DRIVER);
            Connection cn = DriverManager.getConnection(DB_URL,USER,PASS);
            Statement smt = cn.createStatement();
            ResultSet rs = smt.executeQuery("select*from tambah_deposit where No_deposit = '"+no_dep+"'");
            while(rs.next()){
                if(rs.getString("Aktivitas").equals("Tambahkan Saldo Deposit"))
                    total+=Long.parseLong(rs.getString("Tambah"));
            }
        }catch (Exception e){
            e.printStackTrace();
            }
        return set_Rp(total);
    }

    private long get_totrans(String no_dep) {
        long tot_trans = 0;
        try{
            Class.forName(JDBC_DRIVER);
            Connection cn = DriverManager.getConnection(DB_URL,USER,PASS);
            Statement smt = cn.createStatement();
            ResultSet rs = smt.executeQuery("select*from nota where No_deposit = '"+no_dep+"'");
            while(rs.next()){
                    tot_trans+=Long.parseLong(rs.getString("deposit"));
            }
        }catch (Exception e){
            e.printStackTrace();
            }
        return tot_trans;
    }

    private String get_ket(String no_dep) {
        String ket="Deposit belum dicairkan";
        
        try{
             Class.forName(JDBC_DRIVER);
            Connection cn = DriverManager.getConnection(DB_URL,USER,PASS);
            Statement smt = cn.createStatement();
            ResultSet rs = smt.executeQuery("select*from tambah_deposit where No_deposit = '"+no_dep+"' AND Aktivitas='Cairkan Deposit'");
            while(rs.next()){
               ket=rs.getString("keterangan");
            }
        }catch (Exception e){
            e.printStackTrace();
            }
        return ket;
    }
}
