
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Papa Isam
 */
public class Neraca_keuangan extends javax.swing.JFrame {

    /**
     * Creates new form Neraca_keuangan
     */
    
    private DefaultTableModel mdl = new DefaultTableModel(){
        
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    
    private DefaultTableModel mdl2 = new DefaultTableModel(){
        
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    public Neraca_keuangan() {
        initComponents();
        Date ys = new Date();
        SimpleDateFormat dt = new SimpleDateFormat("dd/MM/yyyy");
        lbl_tgl.setText(dt.format(ys));
        mdl.addColumn("No");
        mdl.addColumn("Tanggal");
        mdl.addColumn("Penjualan");
        mdl.addColumn("Piutang");
        mdl.addColumn("Pengeluaran");
        mdl.addColumn("Total Omset");
        jTable1.setModel(mdl);
        mdl2.addColumn("No.");
        mdl2.addColumn("No. Transaksi");
        mdl2.addColumn("Total Transaksi");
        mdl2.addColumn("No. Piutang");
        mdl2.addColumn("Jumlah Piutang");
        mdl2.addColumn("No. Slip");
        mdl2.addColumn("Total Pembayaran");
        jTable2.setModel(mdl2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        awal_tanggal = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        sampai_tanggal = new com.toedter.calendar.JDateChooser();
        tmb_cari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        Tampilkan = new javax.swing.JButton();
        Cetak = new javax.swing.JButton();
        bersihkan = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lbl_tgl = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbl_penjualanhar = new javax.swing.JLabel();
        lbl_pengeluaranhar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_omsethar = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbl_piutanghar = new javax.swing.JLabel();
        Cetak_lap = new javax.swing.JButton();
        Cetak_lap1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lbl_penjualan = new javax.swing.JLabel();
        lbl_pengeluaran = new javax.swing.JLabel();
        lbl_omset = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbl_piutang = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1350, 700));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LAPORAN NERACA KEUANGAN TB. RIZKY PUTRA");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Dari Tanggal");

        awal_tanggal.setDateFormatString("dd MMM, yyyy");
        awal_tanggal.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Sampai Tanggal");

        sampai_tanggal.setDateFormatString("dd MMM, yyyy");
        sampai_tanggal.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        tmb_cari.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tmb_cari.setText("Cari");
        tmb_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmb_cariActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LAPORAN NERACA KEUANGAN HARIAN");

        Tampilkan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Tampilkan.setText("Tampilkan Laporan");
        Tampilkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TampilkanActionPerformed(evt);
            }
        });

        Cetak.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Cetak.setText("Cetak Laporan");
        Cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CetakActionPerformed(evt);
            }
        });

        bersihkan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bersihkan.setText("Bersihkan");
        bersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bersihkanActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Tanggal :");

        lbl_tgl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_tgl.setText("Tanggal :");

        jPanel4.setBackground(new java.awt.Color(51, 255, 255));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Total Penjualan       :");

        lbl_penjualanhar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_penjualanhar.setText("Rp 0,00");

        lbl_pengeluaranhar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_pengeluaranhar.setText("Rp 0,00");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Total Pengeluaran    :");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Total Omset Harian :");

        lbl_omsethar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_omsethar.setText("Rp 0,00");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Total Piutang           :");

        lbl_piutanghar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_piutanghar.setText("Rp 0,00");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_omsethar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_pengeluaranhar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_penjualanhar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lbl_piutanghar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbl_penjualanhar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(lbl_piutanghar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbl_pengeluaranhar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_omsethar))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_tgl))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Tampilkan)
                                .addGap(18, 18, 18)
                                .addComponent(Cetak)
                                .addGap(18, 18, 18)
                                .addComponent(bersihkan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbl_tgl))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tampilkan)
                            .addComponent(Cetak)
                            .addComponent(bersihkan))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(18, Short.MAX_VALUE))))
        );

        Cetak_lap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Cetak_lap.setText("Cetak Laporan");
        Cetak_lap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cetak_lapActionPerformed(evt);
            }
        });

        Cetak_lap1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Cetak_lap1.setText("Bersihkan Table");
        Cetak_lap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cetak_lap1ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(51, 255, 255));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Total Penjualan       :");

        lbl_penjualan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_penjualan.setText("Rp 0,00");

        lbl_pengeluaran.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_pengeluaran.setText("Rp 0,00");

        lbl_omset.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_omset.setText("Rp 0,00");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Total Omset            :");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Total Pengeluaran   :");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Total Piutang          :");

        lbl_piutang.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_piutang.setText("Rp 0,00");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_penjualan, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(lbl_pengeluaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_omset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_piutang, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_penjualan)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lbl_piutang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lbl_pengeluaran))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lbl_omset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(awal_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sampai_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tmb_cari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Cetak_lap)
                                        .addGap(37, 37, 37)
                                        .addComponent(Cetak_lap1)
                                        .addGap(39, 39, 39)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(7, 7, 7)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1379, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1076, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(awal_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(sampai_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tmb_cari))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Cetak_lap)
                                .addComponent(Cetak_lap1))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(103, 103, 103))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tmb_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmb_cariActionPerformed
        // TODO add your handling code here:
        bersihkan();
        SimpleDateFormat dt = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat dt2 = new SimpleDateFormat("dd/MM/yyyy");
        long penjualan=0,pengeluaran=0,piutang=0;
        int i=1;
        tot_penjualan=0;
        tot_pengeluaran=0;
        Calendar start = Calendar.getInstance();
        start.setTime(awal_tanggal.getDate());

        Calendar end = Calendar.getInstance();
        end.setTime(sampai_tanggal.getDate());
        tgl=dt2.format(awal_tanggal.getDate())+" s/d "+dt2.format(sampai_tanggal.getDate());
        while( !start.after(end)){
            Date targetDay = start.getTime();
            penjualan = hitung_penjualan(dt.format(targetDay));
            piutang=hitung_piutang(dt.format(targetDay));
            pengeluaran = hitung_pengeluaran(dt.format(targetDay));
            tot_penjualan+=penjualan;
            tot_piutang+=piutang;
            tot_pengeluaran += pengeluaran;
            mdl.addRow(new Object [] {i,dt2.format(targetDay),set_Rp(penjualan),set_Rp(piutang),set_Rp(pengeluaran),set_Rp(penjualan-pengeluaran)});
            start.add(Calendar.DATE, 1);
            i++;
        }
        lbl_penjualan.setText(set_Rp(tot_penjualan));
        lbl_piutang.setText(set_Rp(tot_piutang));
        lbl_pengeluaran.setText(set_Rp(tot_pengeluaran));
        lbl_omset.setText(set_Rp(tot_penjualan-(tot_piutang+tot_pengeluaran)));
    }//GEN-LAST:event_tmb_cariActionPerformed

    private void Cetak_lapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cetak_lapActionPerformed
        // TODO add your handling code here:
        Date ys = new Date();
        SimpleDateFormat dt = new SimpleDateFormat("dd/MM/yyyy kk:mm");
        
        try{
            HashMap parameter = new HashMap();
            File file = new File("src/Neraca_keuangan.jasper");
            parameter.put("Tanggal",tgl);
            parameter.put("tot_penjualan",set_Rp(tot_penjualan));
            parameter.put("tot_pengeluaran",set_Rp(tot_pengeluaran));
            parameter.put("piutang",set_Rp(tot_piutang));
            parameter.put("omset",set_Rp(tot_penjualan -(tot_piutang+tot_pengeluaran)));
            JasperReport jp = (JasperReport) JRLoader.loadObject(file);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jp,parameter,new JRTableModelDataSource(mdl));
            JasperViewer.viewReport(jasperPrint,false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Data tidak dapat dicetak!"+e.getMessage(),"Informasi",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Cetak_lapActionPerformed

    private void Cetak_lap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cetak_lap1ActionPerformed
        // TODO add your handling code here:
        bersihkan();
        lbl_penjualan.setText("Rp 0,00");
        lbl_piutang.setText("Rp 0,00");
        lbl_pengeluaran.setText("Rp 0,00");
        lbl_omset.setText("Rp 0,00");
        awal_tanggal.setDate(null);
        sampai_tanggal.setDate(null);
    }//GEN-LAST:event_Cetak_lap1ActionPerformed

    private void TampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TampilkanActionPerformed
        // TODO add your handling code here:
        bersihkan2();
        Date ys = new Date();
        SimpleDateFormat dt = new SimpleDateFormat("yyyy-MM-dd");
        int i=1,tot_brs=brs_penjualan(dt.format(ys)),temp=brs_pengeluaran(dt.format(ys));
        
        if(tot_brs<temp)
            tot_brs = temp;
        
        while(i<=tot_brs){
            mdl2.addRow(new Object [] {i,"-","Rp 0,00","-","Rp 0,00","-","Rp 0,00"});
            i++;
        }
        isi_penjuan(dt.format(ys));
        isi_piutang(dt.format(ys));
        isi_pengeluaran(dt.format(ys));
        lbl_penjualanhar.setText(set_Rp(tot_penjualanhar));
        lbl_pengeluaranhar.setText(set_Rp(tot_pengeluaranhar));
        lbl_piutanghar.setText(set_Rp(tot_piutanghar));
        lbl_omsethar.setText(set_Rp(tot_penjualanhar-(tot_piutanghar+tot_pengeluaranhar)));
    }//GEN-LAST:event_TampilkanActionPerformed

    private void CetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CetakActionPerformed
        // TODO add your handling code here:
        Date ys = new Date();
        SimpleDateFormat dt = new SimpleDateFormat("dd/MM/yyyy kk:mm");
        
        try{
            HashMap parameter = new HashMap();
            File file = new File("src/Neraca_harian.jasper");
            parameter.put("tanggal",dt.format(ys));
            parameter.put("penjualan",set_Rp(tot_penjualanhar));
            parameter.put("piutang",set_Rp(tot_piutanghar));
            parameter.put("pengeluaran",set_Rp(tot_pengeluaranhar));
            parameter.put("omset",set_Rp(tot_penjualanhar - (tot_piutanghar+tot_pengeluaranhar)));
            JasperReport jp = (JasperReport) JRLoader.loadObject(file);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jp,parameter,new JRTableModelDataSource(mdl2));
            JasperViewer.viewReport(jasperPrint,false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Data tidak dapat dicetak!"+e.getMessage(),"Informasi",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CetakActionPerformed

    private void bersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bersihkanActionPerformed
        // TODO add your handling code here:
        bersihkan2();
        lbl_penjualanhar.setText("Rp 0,00");
        lbl_pengeluaranhar.setText("Rp 0,00");
        lbl_piutanghar.setText("Rp 0,00");
        lbl_omsethar.setText("Rp 0,00");
    }//GEN-LAST:event_bersihkanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Neraca_keuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Neraca_keuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Neraca_keuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Neraca_keuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Neraca_keuangan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cetak;
    private javax.swing.JButton Cetak_lap;
    private javax.swing.JButton Cetak_lap1;
    private javax.swing.JButton Tampilkan;
    private com.toedter.calendar.JDateChooser awal_tanggal;
    private javax.swing.JButton bersihkan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lbl_omset;
    private javax.swing.JLabel lbl_omsethar;
    private javax.swing.JLabel lbl_pengeluaran;
    private javax.swing.JLabel lbl_pengeluaranhar;
    private javax.swing.JLabel lbl_penjualan;
    private javax.swing.JLabel lbl_penjualanhar;
    private javax.swing.JLabel lbl_piutang;
    private javax.swing.JLabel lbl_piutanghar;
    private javax.swing.JLabel lbl_tgl;
    private com.toedter.calendar.JDateChooser sampai_tanggal;
    private javax.swing.JButton tmb_cari;
    // End of variables declaration//GEN-END:variables

    static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
    static final String DB_URL = "jdbc:mysql://localhost/TB_RP";
    static final String USER = "root";
    static final String PASS = "";
    
    long tot_penjualan;
    long tot_pengeluaran;
    long tot_piutang;
    long tot_penjualanhar;
    long tot_piutanghar;
    long tot_pengeluaranhar;
    String tgl;
    
    public String set_Rp(Long bil){
        DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
        DecimalFormatSymbols formatRp = new DecimalFormatSymbols();

        formatRp.setCurrencySymbol("Rp ");
        formatRp.setMonetaryDecimalSeparator(',');
        formatRp.setGroupingSeparator('.');

        kursIndonesia.setDecimalFormatSymbols(formatRp);
        
        return kursIndonesia.format(bil);
    }
    
    public long hitung_penjualan(String tgl){
        long penjualan=0;
        
        try{
            Class.forName(JDBC_DRIVER);
            Connection cn = DriverManager.getConnection(DB_URL,USER,PASS);
            Statement smt = cn.createStatement();
            ResultSet rs = smt.executeQuery("select * from nota where Tgl_trans = '" +tgl+"'");
            while(rs.next()){
                    penjualan += Long.parseLong(rs.getString("Total"));
            }
            rs.close();
            smt.close();
            cn.close();
        } catch (Exception e){
                e.printStackTrace();
            }
        return penjualan;
    }
    
    public long hitung_pengeluaran(String tgl){
        long pengeluaran=0;
        
        try{
            Class.forName(JDBC_DRIVER);
            Connection cn = DriverManager.getConnection(DB_URL,USER,PASS);
            Statement smt = cn.createStatement();
            ResultSet rs = smt.executeQuery("select * from pengeluaran where Tgl_slip = '" +tgl+"'");
            while(rs.next()){
                    pengeluaran += Long.parseLong(rs.getString("Total_bayar"));
            }
            rs.close();
            smt.close();
            cn.close();
        } catch (Exception e){
                e.printStackTrace();
            }
        return pengeluaran;
    }
    
    public void bersihkan(){
        int j_brs = mdl.getRowCount()-1;
        int i = j_brs;
        while(i>=0){
            mdl.removeRow(i);
            i=i-1;
        }
    }
    
    public void bersihkan2(){
        int j_brs = mdl2.getRowCount()-1;
        int i = j_brs;
        while(i>=0){
            mdl2.removeRow(i);
            i=i-1;
        }
    }
    
    public int brs_penjualan(String tgl){
        int brs=0;
        try{
            Class.forName(JDBC_DRIVER);
            Connection cn = DriverManager.getConnection(DB_URL,USER,PASS);
            Statement smt = cn.createStatement();
            ResultSet rs = smt.executeQuery("select * from nota where Tgl_trans = '" +tgl+"'");
            rs.last();
            brs=rs.getRow();
        }
        catch (Exception e){
                e.printStackTrace();
            }
        return brs;
    }
    
    public void isi_penjuan(String tgl){
        int i=0;
        tot_penjualanhar=0;
        try{
            Class.forName(JDBC_DRIVER);
            Connection cn = DriverManager.getConnection(DB_URL,USER,PASS);
            Statement smt = cn.createStatement();
            ResultSet rs = smt.executeQuery("select * from nota where Tgl_trans = '" +tgl+"'");
            while(rs.next()){
                jTable2.getModel().setValueAt(rs.getString("No_trans"),i,1);
                jTable2.getModel().setValueAt(set_Rp(Long.parseLong(rs.getString("Total"))),i,2);
                tot_penjualanhar+=Long.parseLong(rs.getString("Total"));
                i++;
            }
                
        }
        catch (Exception e){
                e.printStackTrace();
            }
    }
    public int brs_pengeluaran(String tgl){
        int brs=0;
        try{
            Class.forName(JDBC_DRIVER);
            Connection cn = DriverManager.getConnection(DB_URL,USER,PASS);
            Statement smt = cn.createStatement();
            ResultSet rs = smt.executeQuery("select * from pengeluaran where Tgl_slip = '" +tgl+"'");
            rs.last();
            brs=rs.getRow();
        }
        catch (Exception e){
                e.printStackTrace();
            }
        return brs;
    }
    
    public void isi_pengeluaran(String tgl){
        int i=0;
        tot_pengeluaranhar=0;
        try{
            Class.forName(JDBC_DRIVER);
            Connection cn = DriverManager.getConnection(DB_URL,USER,PASS);
            Statement smt = cn.createStatement();
            ResultSet rs = smt.executeQuery("select * from pengeluaran where Tgl_slip = '" +tgl+"'");
            while(rs.next()){
                jTable2.getModel().setValueAt(rs.getString("No_slip"),i,5);
                jTable2.getModel().setValueAt(set_Rp(Long.parseLong(rs.getString("Total_bayar"))),i,6);
                tot_pengeluaranhar+=Long.parseLong(rs.getString("Total_bayar"));
                i++;
            }
                
        }
        catch (Exception e){
                e.printStackTrace();
            }
    }

    private long hitung_piutang(String tanggal) {
        long piutang=0;
        try{
            Class.forName(JDBC_DRIVER);
            Connection cn = DriverManager.getConnection(DB_URL,USER,PASS);
            Statement smt = cn.createStatement();
            ResultSet rs = smt.executeQuery("select * from piutang where Tgl_trans = '" +tanggal+"'");
            while(rs.next()){
                   piutang += Long.parseLong(rs.getString("Sisa_piutang"));
            }
            rs.close();
            smt.close();
            cn.close();
        } catch (Exception e){
                e.printStackTrace();
            }
        
        return piutang;
    }

    private void isi_piutang(String tanggal) {
        int i=0;
        tot_piutanghar=0;
        try{
            Class.forName(JDBC_DRIVER);
            Connection cn = DriverManager.getConnection(DB_URL,USER,PASS);
            Statement smt = cn.createStatement();
            ResultSet rs = smt.executeQuery("select * from piutang where Tgl_trans = '" +tanggal+"'");
            while(rs.next()){
                jTable2.getModel().setValueAt(rs.getString("No_piutang"),i,3);
                jTable2.getModel().setValueAt(set_Rp(Long.parseLong(rs.getString("Sisa_piutang"))),i,4);
                tot_piutanghar+=Long.parseLong(rs.getString("Sisa_piutang"));
                i++;
            }
                
        }
        catch (Exception e){
                e.printStackTrace();
            }
    }
}
