
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.*;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Papa Isam
 */
public class Pengeluaran extends javax.swing.JFrame {

    /**
     * Creates new form Pengeluaran
     */
    private DefaultTableModel mdl = new DefaultTableModel(){
        
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    
    public Pengeluaran() {
        initComponents();
        mdl.addColumn("No.");
        mdl.addColumn("No. Slip");
        mdl.addColumn("Jenis pembayaran");
        mdl.addColumn("Tanggal Pembayaran");
        mdl.addColumn("Pembayaran Kepada");
        mdl.addColumn("Penerima");
        mdl.addColumn("No. Kwitansi");
        mdl.addColumn("Pembayaran Untuk");
        mdl.addColumn("Terbilang");
        mdl.addColumn("Jumlah Pembayaran");
        jTable1.setModel(mdl);
        txt_terbilang.setLineWrap(true);
        txtbyr_unt.setLineWrap(true);
        lbl_totbyr.setText("");
        lbl_sisabyr.setText("");
        lbl_byrke.setText("");
        total.setText("");
        sisa.setText("");
        pembayaranke.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtbyr_kpd = new javax.swing.JTextField();
        txt_penerima = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_jumbyr = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_terbilang = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtbyr_unt = new javax.swing.JTextArea();
        batal = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtno_kwitansi = new javax.swing.JTextField();
        lbl_nonota = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        total = new javax.swing.JLabel();
        sisa = new javax.swing.JLabel();
        pembayaranke = new javax.swing.JLabel();
        lbl_totbyr = new javax.swing.JLabel();
        lbl_sisabyr = new javax.swing.JLabel();
        lbl_byrke = new javax.swing.JLabel();
        lbl_totbyr1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_key = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tgl_awl = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        tgl_akhir = new com.toedter.calendar.JDateChooser();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        lbl_totalbyr = new javax.swing.JLabel();
        simpan1 = new javax.swing.JButton();
        Batalkan_slip = new javax.swing.JButton();
        Hapus_data = new javax.swing.JButton();
        Cetak_laporan = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1350, 700));

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Pencatatan Pengeluaran TB. Rizky Putra");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));
        jPanel1.setForeground(new java.awt.Color(204, 255, 204));

        txtbyr_kpd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtbyr_kpd.setPreferredSize(new java.awt.Dimension(8, 28));
        txtbyr_kpd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbyr_kpdKeyPressed(evt);
            }
        });

        txt_penerima.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_penerima.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_penerimaKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Rp ");

        txt_jumbyr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_jumbyr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_jumbyrFocusLost(evt);
            }
        });
        txt_jumbyr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_jumbyrKeyPressed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txt_terbilang.setColumns(20);
        txt_terbilang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_terbilang.setRows(5);
        txt_terbilang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_terbilangKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txt_terbilang);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtbyr_unt.setColumns(20);
        txtbyr_unt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtbyr_unt.setRows(5);
        txtbyr_unt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbyr_untKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(txtbyr_unt);

        batal.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        batal.setText("Batalkan");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });

        simpan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Pembayaran Untuk");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Terbilang");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Total Pembayaran");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Diterima Oleh");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel5.setText("(Nama Penerima)");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Pembayaran Kepada");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel3.setText("(Nama Distributor/Perusahaan/Toko)");

        txtno_kwitansi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtno_kwitansi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtno_kwitansiFocusLost(evt);
            }
        });
        txtno_kwitansi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtno_kwitansiActionPerformed(evt);
            }
        });
        txtno_kwitansi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtno_kwitansiKeyPressed(evt);
            }
        });

        lbl_nonota.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_nonota.setText("Nomor Kwitansi");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Jenis Pembayaran");

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Biaya Operasional", "Pembayaran Kredit", "Gaji Karyawan", "Pembayaran Barang", "Lain-lain" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 26)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Input Data Pengeluaran");

        jPanel5.setBackground(new java.awt.Color(102, 255, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        total.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        total.setText("Total Pembayaran");

        sisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sisa.setText("Sisa pembayaran");

        pembayaranke.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pembayaranke.setText("Pembayaran ke-");

        lbl_totbyr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_totbyr.setText("Total Pembayaran");

        lbl_sisabyr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_sisabyr.setText("Sisa pembayaran");

        lbl_byrke.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_byrke.setText("Pembayaran ke-");

        lbl_totbyr1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_totbyr1.setText("Keterangan");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_totbyr)
                            .addComponent(lbl_sisabyr)
                            .addComponent(lbl_byrke))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pembayaranke)
                            .addComponent(sisa)
                            .addComponent(total)))
                    .addComponent(lbl_totbyr1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(lbl_totbyr1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total)
                    .addComponent(lbl_totbyr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sisa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_sisabyr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pembayaranke)
                    .addComponent(lbl_byrke))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(lbl_nonota))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtno_kwitansi, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_penerima, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_jumbyr, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(simpan)
                        .addGap(91, 91, 91)
                        .addComponent(batal)
                        .addGap(105, 105, 105))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtbyr_kpd, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtno_kwitansi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nonota))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtbyr_kpd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_penerima, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_jumbyr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(batal)
                    .addComponent(simpan))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 26)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Laporan Pengeluaran");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Kunci Pencarian");

        txt_key.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Dari Tanggal");

        tgl_awl.setDateFormatString(" d/MM/yyyy");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Sampai Tanggal");

        tgl_akhir.setDateFormatString("d/MM/yyyy");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Semua Pembayaran", "Tujuan Pembayaran", "Nomor Slip", "Nomor Kwitansi" }));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Data Harian");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Total Pembayaran :");

        lbl_totalbyr.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_totalbyr.setText("Rp 0,00");

        simpan1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        simpan1.setText("Cetak Slip");
        simpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan1ActionPerformed(evt);
            }
        });

        Batalkan_slip.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Batalkan_slip.setText("Batalkan Slip");
        Batalkan_slip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Batalkan_slipActionPerformed(evt);
            }
        });

        Hapus_data.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Hapus_data.setText("Hapus Data Pengeluaran");
        Hapus_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hapus_dataActionPerformed(evt);
            }
        });

        Cetak_laporan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Cetak_laporan.setText("Cetak Laporan");
        Cetak_laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cetak_laporanActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 888, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(txt_key, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(tgl_awl, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tgl_akhir, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 145, Short.MAX_VALUE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_totalbyr, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(simpan1)
                                .addGap(57, 57, 57)
                                .addComponent(Batalkan_slip)
                                .addGap(48, 48, 48)
                                .addComponent(Cetak_laporan)
                                .addGap(48, 48, 48)
                                .addComponent(Hapus_data)))
                        .addGap(88, 88, 88))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(txt_key, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14)
                    .addComponent(tgl_awl, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel15)
                    .addComponent(tgl_akhir, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lbl_totalbyr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Batalkan_slip)
                        .addComponent(Cetak_laporan)
                        .addComponent(simpan1))
                    .addComponent(Hapus_data))
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 1351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1174, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1261, 1261, 1261)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(878, 1154, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbyr_kpdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbyr_kpdKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
            txt_penerima.requestFocus();
    }//GEN-LAST:event_txtbyr_kpdKeyPressed

    private void txt_penerimaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_penerimaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
            txt_jumbyr.requestFocus();
    }//GEN-LAST:event_txt_penerimaKeyPressed

    private void txt_jumbyrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jumbyrKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
            txt_terbilang.requestFocus();
    }//GEN-LAST:event_txt_jumbyrKeyPressed

    private void txt_terbilangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_terbilangKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
            txtno_kwitansi.requestFocus();
    }//GEN-LAST:event_txt_terbilangKeyPressed

    private void txtno_kwitansiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtno_kwitansiActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_txtno_kwitansiActionPerformed

    private void txtno_kwitansiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtno_kwitansiKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
           txtbyr_kpd.requestFocus();
    }//GEN-LAST:event_txtno_kwitansiKeyPressed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        String pil=jComboBox2.getSelectedItem().toString();
        if(data_validation()){
            if(pil.equals("Pembayaran Kredit")){
                if(Long.parseLong(txt_jumbyr.getText().trim())<=sisa_byr){
                    if(Update_kredit()>0)
                       simpan_data();
                }
                else{
                    JOptionPane.showMessageDialog(this,"Nomimal pembayaran tidak sesuai!","Informasi",JOptionPane.INFORMATION_MESSAGE);
                    txt_jumbyr.setText("");
                    txt_terbilang.setText("");
                }
            }
            else
                simpan_data();
        }
        else
            JOptionPane.showMessageDialog(this,"Data belum lengkap","Informasi",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_simpanActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        // TODO add your handling code here:
        bersihkan_inputan();
    }//GEN-LAST:event_batalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        bersihkan_Table();
        SimpleDateFormat dt = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat dt2 = new SimpleDateFormat("dd/MM/yyyy");
        String pil = jComboBox1.getSelectedItem().toString();
        String sql;
        switch (pil) {
            case "Semua Pembayaran":
                sql = "select * from pengeluaran where Tgl_slip between '"+String.valueOf(dt.format(tgl_awl.getDate()))+"' AND '"+String.valueOf(dt.format(tgl_akhir.getDate()))+"' order by No_slip asc";
                pencarian = "data pembayaran "+String.valueOf(dt2.format(tgl_awl.getDate()))+" sampai "+String.valueOf(dt2.format(tgl_akhir.getDate()));
                break;
            case "Tujuan Pembayaran":
                sql = "select * from pengeluaran where Bayar_kepada like '%"+txt_key.getText().trim()+"%' order by No_slip asc";
                pencarian = "data pembayaran dengan Tujuan Pembayaran: "+txt_key.getText().trim();
                break;
            case "Nomor Slip":
                sql = "select * from pengeluaran where No_Slip = '"+txt_key.getText().trim()+"'";
                pencarian= "data pembayaran dengan Nomor Slip: "+txt_key.getText().trim();
                break;
            default:
                sql = "select * from pengeluaran where No_kwitansi = '"+txt_key.getText().trim()+"' AND Tgl_slip between '"+String.valueOf(dt.format(tgl_awl.getDate()))+"' AND '"+String.valueOf(dt.format(tgl_akhir.getDate()))+"' order by No_slip asc";
                pencarian = "data pembayaran No. Kwitansi: "+txt_key.getText().trim()+" dan "+String.valueOf(dt2.format(tgl_awl.getDate()))+" sampai "+String.valueOf(dt2.format(tgl_akhir.getDate()));
                break;
        }
        create_table(sql);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void simpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan1ActionPerformed
        // TODO add your handling code here:
        int col = jTable1.getSelectedRow();
        if(col>=0){
            try{
                    Class.forName(JDBC_DRIVER);
                    Connection cn = DriverManager.getConnection(DB_URL,USER,PASS);
                    HashMap parameter = new HashMap();
                    JasperDesign jdesign = JRXmlLoader.load("src/Slip.jrxml");
                    parameter.put("No_slip",jTable1.getModel().getValueAt(col,1).toString());
                    parameter.put("Time",jTable1.getModel().getValueAt(col,3).toString());
                    parameter.put("untuk",jTable1.getModel().getValueAt(col,4).toString());
                    parameter.put("penerima",jTable1.getModel().getValueAt(col,5).toString());
                    parameter.put("jumlah",jTable1.getModel().getValueAt(col,9).toString());
                    parameter.put("terbilang",jTable1.getModel().getValueAt(col,8).toString());
                    parameter.put("untuk_bayar",jTable1.getModel().getValueAt(col,7).toString());
                    String query = "select * from pengeluaran";
                    JRDesignQuery updateQuery = new JRDesignQuery();
                    updateQuery.setText(query);
                    jdesign.setQuery(updateQuery);
                    JasperReport jreport = JasperCompileManager.compileReport(jdesign);
                    JasperPrint jprint = JasperFillManager.fillReport(jreport,parameter,cn);
                    JasperViewer.viewReport(jprint,false);
                    cn.close();
            }catch (Exception e){
                e.printStackTrace();
                }
        }
        else
            JOptionPane.showMessageDialog(this,"Tidak ada item terpilih!","Informasi",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_simpan1ActionPerformed

    private void Batalkan_slipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Batalkan_slipActionPerformed
        // TODO add your handling code here:
        Date ys = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat s2 = new SimpleDateFormat("kk:mm:ss");
        String tgl = s.format(ys);
        String wkt = s2.format(ys);
        int col=jTable1.getSelectedRow();
        if(col>=0){
                String pesan = "Anda yakin menghapus Slip no: "+jTable1.getModel().getValueAt(col,1).toString()+
                               ", untuk pembayaran "+jTable1.getModel().getValueAt(col,7).toString()+"?";
                String dat_hps = "Slip No. "+jTable1.getModel().getValueAt(col,1).toString()+" untuk pembayaran "+jTable1.getModel().getValueAt(col,7).toString();
                int result = JOptionPane.showConfirmDialog(null,pesan,"Confirmation Message",JOptionPane.YES_NO_OPTION);
                if(result == JOptionPane.YES_OPTION){
                    try{
                        if(jTable1.getModel().getValueAt(col,2).toString().equals("Pembayaran Kredit"))
                            update_kredit(jTable1.getModel().getValueAt(col,6).toString());
                        Class.forName(JDBC_DRIVER);
                        Connection cn = DriverManager.getConnection(DB_URL,USER,PASS);
                        Statement smt = cn.createStatement();
                        smt.executeUpdate("delete from pengeluaran where No_slip = '"+jTable1.getModel().getValueAt(col,1)+"' ");
                        smt.executeUpdate("insert into log_hapus (Tgl_hapus,Jam_hapus,Data_dihapus) values"
                              +"('"+tgl+"','"+wkt+"','"+dat_hps+"')");
                        smt.close();
                        cn.close();
                        mdl.removeRow(col);
                        jTable1.setModel(mdl);
                    }catch (Exception e){
                        e.printStackTrace();
                    }
                }
                
        }
        else
            JOptionPane.showMessageDialog(this,"Tidak ada item terpilih!","Informasi",JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_Batalkan_slipActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        bersihkan_Table();
        Date ys = new Date();
        SimpleDateFormat dt = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat dt2 = new SimpleDateFormat("dd/MM/yyyy");

        String tgl = dt.format(ys);
        String sql="select * from pengeluaran where Tgl_slip = '"+tgl+"' order by No_slip asc";
        pencarian = "Data pembayaran pada tanggal "+dt2.format(ys);
        create_table(sql);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Hapus_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hapus_dataActionPerformed
        // TODO add your handling code here:
        int j_brs = jTable1.getRowCount()-1;
        Date ys = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat s2 = new SimpleDateFormat("kk:mm:ss");
        String tgl = s.format(ys);
        String wkt = s2.format(ys);
        String pem_kre="";
        if(j_brs>=0){
            String pesan = "Anda yakin menghapus "+pencarian+"?";
            int result = JOptionPane.showConfirmDialog(null,pesan,"Confirmation Message",JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION){
                try{
                    Class.forName(JDBC_DRIVER);
                    Connection cn = DriverManager.getConnection(DB_URL,USER,PASS);
                    Statement smt = cn.createStatement();
                    int i = j_brs;
                    while(i>=0){
                        if(!jTable1.getModel().getValueAt(i,2).toString().equals("Pembayaran Kredit")){
                            smt.executeUpdate("delete from pengeluaran where No_slip = '"+jTable1.getModel().getValueAt(i,1)+"' "); 
                            mdl.removeRow(i);
                        }
                        else
                            pem_kre="Ada";
                        i=i-1;
                    }
                    if(pem_kre.equals("Ada"))
                        JOptionPane.showMessageDialog(this,"Tidak dapat menghapus data Pembayaran Kredit","Informasi",JOptionPane.INFORMATION_MESSAGE);
                    smt.executeUpdate("insert into log_hapus (Tgl_hapus,Jam_hapus,Data_dihapus) values"
                              +"('"+tgl+"','"+wkt+"','"+pencarian+"')");
                } catch (Exception e){
                    e.printStackTrace();
                    }
            }
        }
        else
            JOptionPane.showMessageDialog(this,"Tidak ada data terhapus!","Informasi",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_Hapus_dataActionPerformed

    private void Cetak_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cetak_laporanActionPerformed
        // TODO add your handling code here:
        Date ys = new Date();
        SimpleDateFormat dt = new SimpleDateFormat("dd/MM/yyyy kk:mm");
        
        try{
            HashMap parameter = new HashMap();
            File file = new File("src/pengeluaran.jasper");
            parameter.put("jenis",pencarian);
            parameter.put("time",dt.format(ys));
            parameter.put("total",set_Rp(tot_byr));
            JasperReport jp = (JasperReport) JRLoader.loadObject(file);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jp,parameter,new JRTableModelDataSource(mdl));
            JasperViewer.viewReport(jasperPrint,false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Data tidak dapat dicetak!"+e.getMessage(),"Informasi",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Cetak_laporanActionPerformed

    private void txt_jumbyrFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_jumbyrFocusLost
        // TODO add your handling code here:
        if(!isNumeric(txt_jumbyr.getText().trim())&& !txt_jumbyr.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Masukkan data yang sesuai","Informasi",JOptionPane.INFORMATION_MESSAGE);
            txt_jumbyr.setText("");
            txt_jumbyr.requestFocus();
        }
    }//GEN-LAST:event_txt_jumbyrFocusLost

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        String pil = jComboBox2.getSelectedItem().toString();
        if(pil=="Pembayaran Kredit"){
            lbl_nonota.setText("No. Nota");
            String pesan ="Gunakan pencarian nota?";
            int result = JOptionPane.showConfirmDialog(null,pesan,"Confirmation Message",JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION){
                Cari_Nota2 cn = new Cari_Nota2();
                cn.pg = this;
                cn.setLocationRelativeTo(this);
                cn.setVisible(true);
        //cr.setResizable(false);
                itemTerpilih();
            }
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void txtno_kwitansiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtno_kwitansiFocusLost
        // TODO add your handling code here:
        String pil=jComboBox2.getSelectedItem().toString();
        if(!txtno_kwitansi.getText().trim().equals("")&&pil.equals("Pembayaran Kredit")){
            try{
                Class.forName(JDBC_DRIVER);
                Connection cn = DriverManager.getConnection(DB_URL,USER,PASS);
                Statement smt = cn.createStatement();
                ResultSet rs= smt.executeQuery("select*from kredit where no_nota='"+txtno_kwitansi.getText().trim()+"'");
                rs.next();
                if(rs.getRow()>0&&!txtno_kwitansi.getText().trim().equals("")){
                    txtbyr_kpd.setText(rs.getString("Nama_distributor"));
                    txt_penerima.setText(rs.getString("nama_sales"));
                    lbl_totbyr.setText("Total Pembayaran");
                    lbl_sisabyr.setText("Sisa Pembayaran");
                    lbl_byrke.setText("Pembayaran ke-");
                    total.setText(": "+set_Rp(Long.parseLong(rs.getString("Total_pembayaran"))));
                    sisa_byr=Long.parseLong(rs.getString("Sisa_pembayaran"));
                    sisa.setText(": "+set_Rp(sisa_byr));
                    byrke=Integer.parseInt(rs.getString("pembayaran"))+1;
                    pembayaranke.setText(": "+String.valueOf(byrke));
                    txtbyr_unt.setText("Pembayaran kredit ke-"+byrke+" No. Nota: "+rs.getString("No_nota"));
                }
                else{
                    JOptionPane.showMessageDialog(this,"Data tidak ditemukan!","Informasi",JOptionPane.INFORMATION_MESSAGE);
                    txtno_kwitansi.setText("");
                    txtno_kwitansi.requestFocus();
                }
            } catch (Exception e){
                e.printStackTrace();
            } 
        }
    }//GEN-LAST:event_txtno_kwitansiFocusLost

    private void txtbyr_untKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbyr_untKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbyr_untKeyPressed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pengeluaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Batalkan_slip;
    private javax.swing.JButton Cetak_laporan;
    private javax.swing.JButton Hapus_data;
    private javax.swing.JButton batal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_byrke;
    private javax.swing.JLabel lbl_nonota;
    private javax.swing.JLabel lbl_sisabyr;
    private javax.swing.JLabel lbl_totalbyr;
    private javax.swing.JLabel lbl_totbyr;
    private javax.swing.JLabel lbl_totbyr1;
    private javax.swing.JLabel pembayaranke;
    private javax.swing.JButton simpan;
    private javax.swing.JButton simpan1;
    private javax.swing.JLabel sisa;
    private com.toedter.calendar.JDateChooser tgl_akhir;
    private com.toedter.calendar.JDateChooser tgl_awl;
    private javax.swing.JLabel total;
    private javax.swing.JTextField txt_jumbyr;
    private javax.swing.JTextField txt_key;
    private javax.swing.JTextField txt_penerima;
    private javax.swing.JTextArea txt_terbilang;
    private javax.swing.JTextField txtbyr_kpd;
    private javax.swing.JTextArea txtbyr_unt;
    private javax.swing.JTextField txtno_kwitansi;
    // End of variables declaration//GEN-END:variables

    static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
    static final String DB_URL = "jdbc:mysql://localhost/TB_RP";
    static final String USER = "root";
    static final String PASS = "";
    String no_nota;
    long tot_byr,sisa_byr;
    String pencarian;
    int byrke;
    
public String Ge_slipno(){
        String no_slip = "SL";
        
        Date ys = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyyMMdd");
        no_slip = no_slip.concat(s.format(ys)).concat(no_urut(s.format(ys)));
        return no_slip;
    }
    
    public String no_urut(String tgl){
        int no;
        try{
                Class.forName(JDBC_DRIVER);
                Connection cn = DriverManager.getConnection(DB_URL,USER,PASS);
                Statement smt = cn.createStatement();
                ResultSet rs = smt.executeQuery("select * from pengeluaran where No_Slip like '%" + tgl +"%' order by No_Slip asc");
                rs.last();
                if(rs.getRow()==0)
                    no = 1;
                else
                    no=Integer.parseInt(rs.getString("No_Slip").substring(10,13))+1;
                
                if(no<10)
                    return "00".concat(String.valueOf(no));
                else if(no>=10&&no<100)
                    return "0".concat(String.valueOf(no));
                else
                    return String.valueOf(no);
            } catch (Exception e){
                e.printStackTrace();
                return null;
            } 
    }
    
    public String set_Rp(Long bil){
        DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
        DecimalFormatSymbols formatRp = new DecimalFormatSymbols();

        formatRp.setCurrencySymbol("Rp ");
        formatRp.setMonetaryDecimalSeparator(',');
        formatRp.setGroupingSeparator('.');

        kursIndonesia.setDecimalFormatSymbols(formatRp);
        
        return kursIndonesia.format(bil);
    }
    public void bersihkan_inputan(){
        txtbyr_kpd.setText("");
        txt_penerima.setText("");
        txt_jumbyr.setText("");
        txt_terbilang.setText("");
        txtno_kwitansi.setText("");
        txtbyr_unt.setText("");
        txtbyr_kpd.requestFocus();
        lbl_totbyr.setText("");
        lbl_sisabyr.setText("");
        lbl_byrke.setText("");
        total.setText("");
        sisa.setText("");
        pembayaranke.setText("");
    }
    
    private void bersihkan_Table(){
        int j_brs = jTable1.getRowCount()-1;
        int i = j_brs;
        while(i>=0){
            mdl.removeRow(i);
            i=i-1;
        }
    }
    
    public void create_table(String sql){
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat df2 = new SimpleDateFormat("yyyy-MM-dd");
        int i=1;
        tot_byr = 0;
        try{
                Class.forName(JDBC_DRIVER);
                Connection cn = DriverManager.getConnection(DB_URL,USER,PASS);
                Statement smt = cn.createStatement();
                ResultSet rs = smt.executeQuery(sql);
                while(rs.next()){
                    Date d1 = df2.parse(rs.getString("Tgl_slip"));
                    mdl.addRow(new Object [] {i,rs.getString("No_Slip"),rs.getString("jenis_pembayaran"),df.format(d1).concat(" ").concat(rs.getString("Jam_slip")),
                    rs.getString("Bayar_kepada"),rs.getString("Penerima"),rs.getString("No_kwitansi"),rs.getString("Pembayaran_untuk")
                    ,rs.getString("Terbilang"),set_Rp(Long.parseLong(rs.getString("Total_bayar")))});
                    tot_byr += Long.parseLong(rs.getString("Total_bayar"));
                    i++;
                }
                rs.last();
                if(rs.getRow()==0)
                    JOptionPane.showMessageDialog(this,"Tidak ada data ditemukan!","Informasi",JOptionPane.INFORMATION_MESSAGE);
                lbl_totalbyr.setText(set_Rp(tot_byr));
        } catch (Exception e){
                e.printStackTrace();
            } 
    }
    
    public static boolean isNumeric(String strNum) {
        if (strNum == null) {
            return false;
        }
        try {
            double d = Double.parseDouble(strNum);
        } catch (NumberFormatException nfe) {
            return false;
            }
        return true;
    }

    void itemTerpilih() {
        Cari_Nota2 cn = new Cari_Nota2();
        cn.pg = this;
        txtno_kwitansi.setText(no_nota);
        txtno_kwitansi.requestFocus();
    }

    private boolean data_validation() {
        boolean val=true;
        boolean val1=txtno_kwitansi.getText().trim().equals("")?false:true;
        boolean val2=txtbyr_kpd.getText().trim().equals("")?false:true;
        boolean val3=txt_penerima.getText().trim().equals("")?false:true;
        boolean val4=txt_jumbyr.getText().trim().equals("")?false:true;
        boolean val5=txt_terbilang.getText().trim().equals("")?false:true;
        boolean val6=txtbyr_unt.getText().trim().equals("")?false:true;
        val=val1&&val2&&val3&&val4&&val5&&val6;
        return val;
    }
    
    public void simpan_data(){
        String slip_no = Ge_slipno();
        Date ys = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat s2 = new SimpleDateFormat("kk:mm:ss");
        SimpleDateFormat s3 = new SimpleDateFormat("dd/MM/yyyy kk:mm:ss");
        String tgl = s.format(ys);
        String wkt = s2.format(ys);
        String time = s3.format(ys);
        String pil=jComboBox2.getSelectedItem().toString();
        try{
            Class.forName(JDBC_DRIVER);
            Connection cn = DriverManager.getConnection(DB_URL,USER,PASS);
            Statement smt = cn.createStatement();
            int a = smt.executeUpdate("INSERT INTO Pengeluaran (No_slip,jenis_pembayaran,Tgl_slip,Jam_slip,Bayar_kepada,Penerima,Total_bayar,Terbilang,No_kwitansi,Pembayaran_untuk) values"
                 +"('"+slip_no+"','"+pil+"','"+tgl+"','"+wkt+"','"+txtbyr_kpd.getText().trim()+"','"+txt_penerima.getText().trim()
                 +"','"+txt_jumbyr.getText().trim()+"','"+txt_terbilang.getText().trim()+"','"+txtno_kwitansi.getText().trim()
                 +"','"+txtbyr_unt.getText().trim()+"') ");
            if(a>0){
               String pesan = "Data berhasil disimpan, apakah anda akan mencetak bukti pembayaran?";
               int result = JOptionPane.showConfirmDialog(null,pesan,"Confirmation Message",JOptionPane.YES_NO_OPTION);
               if(result == JOptionPane.YES_OPTION){
                        HashMap parameter = new HashMap();
                        JasperDesign jdesign = JRXmlLoader.load("src/Slip.jrxml");
                        parameter.put("No_slip",slip_no);
                        parameter.put("Time",time);
                        parameter.put("untuk",txtbyr_kpd.getText().trim());
                        parameter.put("penerima",txt_penerima.getText().trim());
                        parameter.put("jumlah",set_Rp(Long.parseLong(txt_jumbyr.getText().trim())));
                        parameter.put("terbilang",txt_terbilang.getText().trim());
                        parameter.put("untuk_bayar",txtbyr_unt.getText().trim());
                        String query = "select * from pengeluaran where No_Slip = '"+slip_no+"'";
                        JRDesignQuery updateQuery = new JRDesignQuery();
                        updateQuery.setText(query);
                        jdesign.setQuery(updateQuery);
                        JasperReport jreport = JasperCompileManager.compileReport(jdesign);
                        JasperPrint jprint = JasperFillManager.fillReport(jreport,parameter,cn);
                        JasperViewer.viewReport(jprint,false);
                    }
                }
                smt.close();
                cn.close();
                bersihkan_inputan();
            }catch (Exception e){
                e.printStackTrace();
                }
    }

    private int Update_kredit() {
        int a=0;
        try{
            Class.forName(JDBC_DRIVER);
            Connection cn = DriverManager.getConnection(DB_URL,USER,PASS);
            Statement smt = cn.createStatement();
            long sisa_pembayaran=sisa_byr-Long.parseLong(txt_jumbyr.getText().trim());
            a=smt.executeUpdate("Update kredit set Sisa_pembayaran='"+sisa_pembayaran+"', pembayaran='"+byrke+"' where no_nota='"+txtno_kwitansi.getText().trim()+"'");
            smt.close();
            cn.close();
        }catch (Exception e){
                e.printStackTrace();
                }
        return a;
    }

    private void update_kredit(String no_nota) {
        try{
            Class.forName(JDBC_DRIVER);
            Connection cn = DriverManager.getConnection(DB_URL,USER,PASS);
            Statement smt = cn.createStatement();
            ResultSet rs = smt.executeQuery("select*from kredit where no_nota='"+no_nota+"'");
            rs.next();
            long sisa=Long.parseLong(rs.getString("Sisa_pembayaran"))+cancel_bayar(no_nota);
            int jum_byr=Integer.parseInt(rs.getString("pembayaran"))-1;
            smt.executeUpdate("Update kredit set Sisa_pembayaran='"+sisa+"',pembayaran='"+jum_byr+"' where no_nota='"+no_nota+"'");
            rs.close();
            smt.close();
            cn.close();
        }catch (Exception e){
                e.printStackTrace();
        }
    }

    private long cancel_bayar(String no_nota) {
        long byr=0;
        try{
            Class.forName(JDBC_DRIVER);
            Connection cn = DriverManager.getConnection(DB_URL,USER,PASS);
            Statement smt = cn.createStatement();
            ResultSet rs = smt.executeQuery("select*from pengeluaran where no_kwitansi='"+no_nota+"' AND jenis_pembayaran='Pembayaran Kredit'");
            rs.next();
            byr=Long.parseLong(rs.getString("Total_bayar"));
            System.out.println(sisa);
        }catch (Exception e){
                e.printStackTrace();
        }
        return byr;
    }
}
