
import java.io.File;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Papa Isam
 */
public class Profit_penjualan extends javax.swing.JFrame {

    /**
     * Creates new form Profit_penjualan
     */
    private DefaultTableModel mdl = new DefaultTableModel(){
        
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    public Profit_penjualan() {
        initComponents();
        mdl.addColumn("No.");
        mdl.addColumn("Kode Barang");
        mdl.addColumn("Nama Barang");
        mdl.addColumn("Barang Terjual");
        mdl.addColumn("Total Penjualan");
        mdl.addColumn("Total Modal");
        mdl.addColumn("Total Keuntungan");
        jTable1.setModel(mdl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        tmb_tranhari = new javax.swing.JButton();
        tmb_cari = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        awal_tanggal = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        sampai_tanggal = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lbl_penjualan = new javax.swing.JLabel();
        lbl_modal = new javax.swing.JLabel();
        lbl_profit = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        bersihkan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(1350, 700));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LAPORAN KEUNTUNGAN PENJUALAN TB. RIZKY PUTRA");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tmb_tranhari.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tmb_tranhari.setText("Transaksi Harian");
        tmb_tranhari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmb_tranhariActionPerformed(evt);
            }
        });

        tmb_cari.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tmb_cari.setText("Cari");
        tmb_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmb_cariActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Dari Tanggal");

        awal_tanggal.setDateFormatString("dd MMM, yyyy");
        awal_tanggal.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Sampai Tanggal");

        sampai_tanggal.setDateFormatString("dd MMM, yyyy");
        sampai_tanggal.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.setBackground(new java.awt.Color(51, 255, 255));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Total Penjualan       :");

        lbl_penjualan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_penjualan.setText("Rp 0,00");

        lbl_modal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_modal.setText("Rp 0,00");

        lbl_profit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_profit.setText("Rp 0,00");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Total Keuntungan   :");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Total Modal            :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_penjualan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(lbl_modal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_profit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lbl_penjualan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(lbl_modal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(lbl_profit))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Cetak Laporan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bersihkan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bersihkan.setText("Bersihkan Table");
        bersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bersihkanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1330, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(awal_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(sampai_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(tmb_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(tmb_tranhari)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jButton1)
                        .addGap(55, 55, 55)
                        .addComponent(bersihkan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tmb_cari)
                        .addComponent(tmb_tranhari))
                    .addComponent(jLabel1)
                    .addComponent(sampai_tanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(awal_tanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(bersihkan))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tmb_tranhariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmb_tranhariActionPerformed
        // TODO add your handling code here:
        bersihkan_Table();
        Date ys = new Date();
        SimpleDateFormat dt2 = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        //  s.format(ys);
        String sql = "select*from transaksi where Tgl_trans= '"+s.format(ys)+"' order by Kd_brg";
        Label = dt2.format(ys);
        tampil_table(sql);
    }//GEN-LAST:event_tmb_tranhariActionPerformed

    private void tmb_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmb_cariActionPerformed
        // TODO add your handling code here:
        bersihkan_Table();
        SimpleDateFormat dt = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat dt2 = new SimpleDateFormat("dd/MM/yyyy");
        String sql = "select * from transaksi where Tgl_trans between '"+dt.format(awal_tanggal.getDate())+"' AND '"+dt.format(sampai_tanggal.getDate())+"' order by Kd_brg";
        Label = dt2.format(awal_tanggal.getDate())+" s/d "+dt2.format(sampai_tanggal.getDate());
        tampil_table(sql);

    }//GEN-LAST:event_tmb_cariActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            HashMap parameter = new HashMap();
            File file = new File("src/Laporan_profit.jasper");
            parameter.put("tgl",Label);
            parameter.put("penjualan",set_Rp(tot_penjualan));
            parameter.put("modal",set_Rp(tot_modal));
            parameter.put("profit",set_Rp(tot_penjualan - tot_modal));
            JasperReport jp = (JasperReport) JRLoader.loadObject(file);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jp,parameter,new JRTableModelDataSource(mdl));
            JasperViewer.viewReport(jasperPrint,false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Data tidak dapat dicetak!"+e.getMessage(),"Informasi",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bersihkanActionPerformed
        // TODO add your handling code here:
        bersihkan_Table();
        awal_tanggal.setDate(null);
        sampai_tanggal.setDate(null);
    }//GEN-LAST:event_bersihkanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profit_penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profit_penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profit_penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profit_penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profit_penjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser awal_tanggal;
    private javax.swing.JButton bersihkan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_modal;
    private javax.swing.JLabel lbl_penjualan;
    private javax.swing.JLabel lbl_profit;
    private com.toedter.calendar.JDateChooser sampai_tanggal;
    private javax.swing.JButton tmb_cari;
    private javax.swing.JButton tmb_tranhari;
    // End of variables declaration//GEN-END:variables
    
    static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
    static final String DB_URL = "jdbc:mysql://localhost/TB_RP";
    static final String USER = "root";
    static final String PASS = "";
    String Label;
    long tot_penjualan;
    long tot_modal;

    public String set_Rp(Long bil){
        DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
        DecimalFormatSymbols formatRp = new DecimalFormatSymbols();

        formatRp.setCurrencySymbol("Rp ");
        formatRp.setMonetaryDecimalSeparator(',');
        formatRp.setGroupingSeparator('.');

        kursIndonesia.setDecimalFormatSymbols(formatRp);
        
        return kursIndonesia.format(bil);
    }
    
    public void bersihkan_Table(){
        int j_brs = mdl.getRowCount()-1;
        int i = j_brs;
        while(i>=0){
            mdl.removeRow(i);
            i=i-1;
        }
        lbl_penjualan.setText("Rp 0,00");
        lbl_modal.setText("Rp 0,00");
        lbl_profit.setText("Rp 0,00");
    }

    private void tampil_table(String sql) {
        int i=0,j=1;double jum=0;
        long tot_pen=0,tot_mo=0;
        String kd="",nm="";
        tot_penjualan = 0;tot_modal=0;
        try{
            Class.forName(JDBC_DRIVER);
            Connection cn = DriverManager.getConnection(DB_URL,USER,PASS);
            Statement smt = cn.createStatement();
            ResultSet rs = smt.executeQuery(sql);
            rs.last();
            int a=rs.getRow()-1;
            if(a>=0){
                rs.first();
                kd=rs.getString("Kd_brg");
                nm=rs.getString("Nm_brg");
                jum=Double.parseDouble(rs.getString("Qty"));
                tot_pen=Long.parseLong(rs.getString("Hrg"))-Long.parseLong(rs.getString("Diskon"));
                tot_mo=Long.parseLong(rs.getString("modal"));
                i++;
                System.out.println(a+","+i);
                while(rs.next()){
                    if(kd.equals(rs.getString("Kd_brg"))){
                        if(i!=a){
                            jum+=Double.parseDouble(rs.getString("Qty"));
                            tot_pen+=Long.parseLong(rs.getString("Hrg"))-Long.parseLong(rs.getString("Diskon"));
                            tot_mo+=Long.parseLong(rs.getString("modal"));
                        }
                        else{
                            jum+=Double.parseDouble(rs.getString("Qty"));
                            tot_pen+=Long.parseLong(rs.getString("Hrg"))-Long.parseLong(rs.getString("Diskon"));
                            tot_mo+=Long.parseLong(rs.getString("modal"));
                            tot_penjualan+=tot_pen;
                            tot_modal+=tot_mo;
                            mdl.addRow(new Object [] {j,kd,nm,jum,set_Rp(tot_pen),set_Rp(tot_mo),set_Rp(tot_pen-tot_mo)});
                        }
                    }
                    else{
                        if(i!=a){
                            mdl.addRow(new Object [] {j,kd,nm,jum,set_Rp(tot_pen),set_Rp(tot_mo),set_Rp(tot_pen-tot_mo)});
                            tot_penjualan+=tot_pen;
                            tot_modal+=tot_mo;
                            j++;
                            kd=rs.getString("Kd_brg");
                            nm=rs.getString("Nm_brg");
                            jum=Double.parseDouble(rs.getString("Qty"));
                            tot_pen=Long.parseLong(rs.getString("Hrg"))-Long.parseLong(rs.getString("Diskon"));
                            tot_mo=Long.parseLong(rs.getString("modal"));
                        }
                        else{
                            mdl.addRow(new Object [] {j,kd,nm,jum,set_Rp(tot_pen),set_Rp(tot_mo),set_Rp(tot_pen-tot_mo)});
                            tot_penjualan+=tot_pen;
                            tot_modal+=tot_mo;
                            kd=rs.getString("Kd_brg");
                            nm=rs.getString("Nm_brg");
                            jum=Double.parseDouble(rs.getString("Qty"));
                            tot_pen=Long.parseLong(rs.getString("Hrg"))-Long.parseLong(rs.getString("Diskon"));
                            tot_mo=Long.parseLong(rs.getString("modal"));
                            mdl.addRow(new Object [] {j,kd,nm,jum,set_Rp(tot_pen),set_Rp(tot_mo),set_Rp(tot_pen-tot_mo)});
                            tot_penjualan+=tot_pen;
                            tot_modal+=tot_mo;
                        }
                    }          
                    i++;
                }
                lbl_penjualan.setText(set_Rp(tot_penjualan));
                lbl_modal.setText(set_Rp(tot_modal));
                lbl_profit.setText(set_Rp(tot_penjualan - tot_modal));
                jTable1.setModel(mdl);
            }
            else{
                JOptionPane.showMessageDialog(this,"Tidak ada data ditemukan!","Informasi",JOptionPane.INFORMATION_MESSAGE);
            }
            rs.close();
            smt.close();
            cn.close();
        }catch (Exception e){
                e.printStackTrace();
            }
    }
}
