
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.InputStreamReader;
import java.sql.*;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Papa Isam
 */
public class transaksi extends javax.swing.JFrame {
    
    private DefaultTableModel mdl = new DefaultTableModel(){
        
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    /**
     * Creates new form transaksi
     */
    public transaksi() {
        initComponents();
        txt_diskon.setText("0");
        txt_diskonnota.setText("0");
        lbl_subtotal.setText(set_Rp(G_subtotal));
        lbl_diskon.setText(set_Rp(G_diskon));
        lbl_total.setText(set_Rp(G_total));
        mdl.addColumn("Kode Barang");
        mdl.addColumn("Nama Barang");
        mdl.addColumn("Quantity");
        mdl.addColumn("Harga Satuan");
        mdl.addColumn("Harga");
        mdl.addColumn("Diskon");
        lbl_nama.setText("");
        lbl_saldo.setText("");
        jTable1.setModel(mdl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tmb_hapus = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txt_diskonnota = new javax.swing.JTextField();
        tmb_cetak = new javax.swing.JButton();
        tmb_batal = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtno_dep = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lbl_nama = new javax.swing.JLabel();
        lbl_saldo = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        cari_dep = new javax.swing.JButton();
        hap_dep = new javax.swing.JButton();
        tmb_tambahdisno = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtkd_brg = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_nmbrg = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Qty = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txt_diskon = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        tmb_tambah = new javax.swing.JButton();
        tmb_tambah1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_subtotal = new javax.swing.JLabel();
        lbl_diskon = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_nmpiutang = new javax.swing.JTextField();
        txt_nohp = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        txt_keterangan = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Qty");

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setPreferredSize(new java.awt.Dimension(1350, 700));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Aplikasi Penjualan TB. Rizky Putra");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        tmb_hapus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tmb_hapus.setText("Hapus");
        tmb_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmb_hapusActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Diskon per Nota");

        txt_diskonnota.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_diskonnotaFocusLost(evt);
            }
        });
        txt_diskonnota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_diskonnotaKeyTyped(evt);
            }
        });

        tmb_cetak.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tmb_cetak.setText("Cetak");
        tmb_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmb_cetakActionPerformed(evt);
            }
        });

        tmb_batal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tmb_batal.setText("Batal Transaksi");
        tmb_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmb_batalActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("No. Deposit");

        txtno_dep.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtno_dep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtno_depFocusLost(evt);
            }
        });
        txtno_dep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtno_depActionPerformed(evt);
            }
        });
        txtno_dep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtno_depKeyPressed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("atau");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Cari No.Deposit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Nama");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Sisa Saldo");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText(":");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText(":");

        lbl_nama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_nama.setText("Nama");

        lbl_saldo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_saldo.setText("Sisa Saldo");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel24.setText("* Isi data berikut jika pembayaran menggunakan deposit");

        cari_dep.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cari_dep.setText("Cari");
        cari_dep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari_depActionPerformed(evt);
            }
        });

        hap_dep.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hap_dep.setText("Hapus");
        hap_dep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hap_depActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtno_dep, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton1))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel21)
                                            .addComponent(jLabel20))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lbl_nama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbl_saldo, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)))))
                            .addComponent(jLabel24)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(cari_dep, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(hap_dep, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtno_dep, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_nama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_saldo)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cari_dep)
                    .addComponent(hap_dep))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tmb_tambahdisno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tmb_tambahdisno.setText("Tambahkan");
        tmb_tambahdisno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmb_tambahdisnoActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Kode Barang");

        txtkd_brg.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtkd_brg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtkd_brgFocusLost(evt);
            }
        });
        txtkd_brg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkd_brgActionPerformed(evt);
            }
        });
        txtkd_brg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtkd_brgKeyPressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Nama Barang");

        txt_nmbrg.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_nmbrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nmbrgActionPerformed(evt);
            }
        });
        txt_nmbrg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nmbrgKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Qty");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Diskon");

        Qty.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Qty.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                QtyFocusLost(evt);
            }
        });
        Qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QtyActionPerformed(evt);
            }
        });
        Qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                QtyKeyPressed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kode Barang", "Nama Barang" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Cari dengan");

        txt_diskon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_diskon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_diskonFocusLost(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rp", "%" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Input Data Barang");

        tmb_tambah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tmb_tambah.setText("Tambah");
        tmb_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmb_tambahActionPerformed(evt);
            }
        });

        tmb_tambah1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tmb_tambah1.setText("Batal");
        tmb_tambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmb_tambah1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nmbrg)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtkd_brg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Qty)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(tmb_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(tmb_tambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 63, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_diskon)))))
                .addContainerGap())
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtkd_brg, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_nmbrg, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(Qty, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_diskon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tmb_tambah1)
                    .addComponent(tmb_tambah))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Diskon :");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Total :");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Sub Total :");

        lbl_subtotal.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_subtotal.setText("0");

        lbl_diskon.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_diskon.setText("0");

        lbl_total.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_total.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_subtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_diskon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_total, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbl_subtotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_diskon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_total))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Pembayaran dengan ");

        jComboBox3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tunai", "Deposit", "Piutang", "Deposit dan Piutang" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Nama");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel25.setText("* Isi data berikut jika pembayaran menggunakan piutang");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("No. Telp/Hp");

        txt_nmpiutang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_nmpiutang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_nmpiutangFocusLost(evt);
            }
        });
        txt_nmpiutang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nmpiutangActionPerformed(evt);
            }
        });
        txt_nmpiutang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nmpiutangKeyPressed(evt);
            }
        });

        txt_nohp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_nohp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_nohpFocusLost(evt);
            }
        });
        txt_nohp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nohpActionPerformed(evt);
            }
        });
        txt_nohp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nohpKeyPressed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Jatuh Tempo");

        jDateChooser1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        txt_keterangan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_keterangan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_keteranganFocusLost(evt);
            }
        });
        txt_keterangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_keteranganActionPerformed(evt);
            }
        });
        txt_keterangan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_keteranganKeyPressed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Keterangan");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel25)
                .addGap(0, 190, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel22)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_keterangan)
                    .addComponent(txt_nohp)
                    .addComponent(txt_nmpiutang)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txt_nmpiutang, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txt_nohp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(txt_diskonnota, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(tmb_tambahdisno, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(tmb_cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(114, 114, 114)
                                .addComponent(tmb_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)
                                .addComponent(tmb_batal)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_diskonnota, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(tmb_tambahdisno))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tmb_hapus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tmb_batal)
                                .addComponent(tmb_cetak))))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tmb_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmb_tambahActionPerformed
        // TODO add your handling code here:
        String kdbrg;
        String nmbrg;
        long hrg_satuan;
        long hrg;
        long diskon;
        String pil = jComboBox2.getSelectedItem().toString();
        
        boolean isi = cek_isitext();
        if(isi==true){
            try{
                Class.forName(JDBC_DRIVER);
                Connection cn = DriverManager.getConnection(DB_URL,USER,PASS);
                Statement smt = cn.createStatement();
                ResultSet rs = smt.executeQuery("select * from barang where Kd_brg = '" + txtkd_brg.getText().trim() +"'");
                rs.next();
                kdbrg = rs.getString("Kd_brg");
                nmbrg = rs.getString("Nm_brg");
                double stok = Double.parseDouble(rs.getString("Stok"));
                double qty = Double.parseDouble(Qty.getText().trim());
                hrg_satuan = Long.parseLong(rs.getString("Harga"));
                hrg = (long) (qty*hrg_satuan);
                
                    if(pil.equals("Rp"))
                          diskon = (long) (Long.parseLong(txt_diskon.getText().trim())*qty);
                    else
                          diskon = Long.parseLong(txt_diskon.getText().trim())*hrg/100;           
                if(qty<=stok){
                    Object[] o = {kdbrg,nmbrg,qty,hrg_satuan,hrg,diskon};
                    mdl.addRow(o);
                    count();
                    set_harga();
                    rs.close();
                    smt.close();
                    cn.close();
                }
                else
                    JOptionPane.showMessageDialog(this,"Stok tidak cukup!","Informasi",JOptionPane.INFORMATION_MESSAGE);
                bersihkan();
        } catch (Exception e){
                e.printStackTrace();
            }
      }
    }//GEN-LAST:event_tmb_tambahActionPerformed

    private void txtkd_brgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkd_brgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkd_brgActionPerformed

    private void txtkd_brgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkd_brgKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            String pil = jComboBox1.getSelectedItem().toString();
            if(pil.equals("Kode Barang")){
                try{
                Class.forName(JDBC_DRIVER);
                Connection cn = DriverManager.getConnection(DB_URL,USER,PASS);
                Statement smt = cn.createStatement();
                ResultSet rs = smt.executeQuery("select * from barang where Kd_brg = '" + txtkd_brg.getText().trim() +"'");
                rs.next();
                int a = rs.getRow();
                if (a>0){
                    Qty.requestFocus();
                    txt_nmbrg.setText(rs.getString("Nm_brg"));
                }
                else{
                    JOptionPane.showMessageDialog(this,"Tidak Ada Data Ditemukan!","Informasi",JOptionPane.INFORMATION_MESSAGE);
                    txtkd_brg.setText("");
                }
                rs.close();
                smt.close();
                cn.close();
                } catch (Exception e){
                e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_txtkd_brgKeyPressed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String pil = jComboBox1.getSelectedItem().toString();
        if(pil.equals("Nama Barang")){
            Cari_barang cr = new Cari_barang();
            cr.tr = this;
            cr.setLocationRelativeTo(this);
            cr.setVisible(true);
            //cr.setResizable(false);
            itemTerpilih();
            Qty.requestFocus();
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void QtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QtyKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            txt_diskon.requestFocus();
        }
    }//GEN-LAST:event_QtyKeyPressed

    private void QtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QtyActionPerformed

    private void tmb_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmb_hapusActionPerformed
        // TODO add your handling code here:
       int col = jTable1.getSelectedRow();
       if(col>=0){
            String pesan = "Anda yakin menghapus:\nKode Barang \t : " +jTable1.getModel().getValueAt(col,0).toString()+
                    "\nNama Barang \t : "+jTable1.getModel().getValueAt(col,1).toString();
       
            int result = JOptionPane.showConfirmDialog(null,pesan,"Confirmation Message",JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION){
                mdl.removeRow(col);
                count();
                set_harga();
            }
       }
       else
           JOptionPane.showMessageDialog(this,"Tidak ada Item yang dipilih!","Informasi",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_tmb_hapusActionPerformed

    private void txt_diskonnotaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_diskonnotaKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txt_diskonnotaKeyTyped

    private void tmb_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmb_cetakActionPerformed
        // TODO add your handling code here:
        String no = Ge_transno();String cr_byr;
        String no_piutang ="-";
        if(jComboBox3.getSelectedItem().equals("Deposit")){
             if(!no_deposit.equals("-")&&!nama_deposit.equals("")&&saldo!=0){
                 if(saldo>=G_total){
                    cr_byr = "Deposit";
                    simpan(no,no_piutang,cr_byr);
                    cetak_nota(no,no_piutang,cr_byr);
                 }
                 else{
                     int result = JOptionPane.showConfirmDialog(null,"Sisa saldo deposit tidak mencukupi, apakah akan melanjutkan dengan pembayaran tunai?","Confirmation Message",JOptionPane.YES_NO_OPTION);
                     if(result == JOptionPane.YES_OPTION){
                        cr_byr = "Deposit dan Tunai";
                        simpan(no,no_piutang,cr_byr);
                        cetak_nota(no,no_piutang,cr_byr);
                     }
                 }
             }
             else
                 JOptionPane.showMessageDialog(this,"Data deposit tidak ditemukan atau saldo deposit sudah habis!","Informasi",JOptionPane.INFORMATION_MESSAGE);
        }
        else if(jComboBox3.getSelectedItem().equals("Piutang")){
            if(!txt_nmpiutang.getText().equals("")&&!txt_nohp.getText().equals("")){
                no_piutang = gene_nopi();
                cr_byr = "Piutang";
                no_deposit="-";
                simpan(no,no_piutang,cr_byr);
                cetak_nota(no,no_piutang,cr_byr);
            }
            else{
                JOptionPane.showMessageDialog(this,"Data Piutang belum terisi lengkap!","Informasi",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else if(jComboBox3.getSelectedItem().equals("Deposit dan Piutang")){
            if(saldo<G_total){
                if(!no_deposit.equals("-")&&!nama_deposit.equals("")&&saldo!=0&&!txt_nmpiutang.getText().equals("")&&!txt_nohp.getText().equals("")){
                    no_piutang = gene_nopi();
                    cr_byr = "Deposit dan Piutang";
                    simpan(no,no_piutang,cr_byr);
                    cetak_nota(no,no_piutang,cr_byr);
                }
                else
                    JOptionPane.showMessageDialog(this,"Data Deposit dan Piutang belum terisi lengkap atau saldo deposit sudah habis!","Informasi",JOptionPane.INFORMATION_MESSAGE);
            }
            else
                JOptionPane.showMessageDialog(this,"Saldo Deposit masih cukup, silahkan lanjutkan transaksi dengan Deposit!","Informasi",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            cr_byr="Tunai";
            no_piutang="-";
            no_deposit="-";
            simpan(no,no_piutang,cr_byr);
            cetak_nota(no,no_piutang,cr_byr);
        }
       
        bersihkan_Table();
        bersihkan();
        txtno_dep.setText("");
        lbl_nama.setText("");
        lbl_saldo.setText("");
        tunai=0;
        deposit=0;
        piutang=0;
    }//GEN-LAST:event_tmb_cetakActionPerformed

    private void txt_nmbrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nmbrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nmbrgActionPerformed

    private void txt_nmbrgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nmbrgKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nmbrgKeyPressed

    private void tmb_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmb_batalActionPerformed
        // TODO add your handling code here:
        bersihkan_Table();
    }//GEN-LAST:event_tmb_batalActionPerformed

    private void QtyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_QtyFocusLost
        // TODO add your handling code here:
        if(!isNumeric(Qty.getText().trim())&& !Qty.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Masukkan data yang sesuai","Informasi",JOptionPane.INFORMATION_MESSAGE);
            Qty.setText("");
            Qty.requestFocus();
        }
        
    }//GEN-LAST:event_QtyFocusLost

    private void txt_diskonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_diskonFocusLost
        // TODO add your handling code here:
        if(!isNumeric(txt_diskon.getText().trim())&& !txt_diskon.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Masukkan data yang sesuai","Informasi",JOptionPane.INFORMATION_MESSAGE);
            txt_diskon.setText("");
            txt_diskon.requestFocus();
        }
        
    }//GEN-LAST:event_txt_diskonFocusLost

    private void txt_diskonnotaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_diskonnotaFocusLost
        // TODO add your handling code here:
        if(!isNumeric(txt_diskonnota.getText().trim())&& !txt_diskonnota.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Masukkan data yang sesuai","Informasi",JOptionPane.INFORMATION_MESSAGE);
            txt_diskonnota.setText("");
            txt_diskonnota.requestFocus();
        }
    }//GEN-LAST:event_txt_diskonnotaFocusLost

    private void txtkd_brgFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtkd_brgFocusLost
        // TODO add your handling code here:
        if(!txtkd_brg.getText().trim().isEmpty()){
            try{
                Class.forName(JDBC_DRIVER);
                Connection cn = DriverManager.getConnection(DB_URL,USER,PASS);
                Statement smt = cn.createStatement();
                ResultSet rs = smt.executeQuery("select * from barang where Kd_brg = '" + txtkd_brg.getText().trim() +"'");
                rs.next();
                int a = rs.getRow();
                if (a>0){
                    Qty.requestFocus();
                    txt_nmbrg.setText(rs.getString("Nm_brg"));
                }
                else{
                    JOptionPane.showMessageDialog(this,"Tidak Ada Data Ditemukan!","Informasi",JOptionPane.INFORMATION_MESSAGE);
                    txtkd_brg.setText("");
                }
                rs.close();
                smt.close();
                cn.close();
                } catch (Exception e){
                e.printStackTrace();
                }
        }
    }//GEN-LAST:event_txtkd_brgFocusLost

    private void tmb_tambahdisnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmb_tambahdisnoActionPerformed
        // TODO add your handling code here:
        count();
        set_harga();
    }//GEN-LAST:event_tmb_tambahdisnoActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void tmb_tambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmb_tambah1ActionPerformed
        // TODO add your handling code here:
        bersihkan();
    }//GEN-LAST:event_tmb_tambah1ActionPerformed

    private void txtno_depFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtno_depFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtno_depFocusLost

    private void txtno_depActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtno_depActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtno_depActionPerformed

    private void txtno_depKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtno_depKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
           try{
              Class.forName(JDBC_DRIVER);
              Connection cn = DriverManager.getConnection(DB_URL,USER,PASS);
              Statement smt = cn.createStatement();
              ResultSet rs = smt.executeQuery("select * from deposit where no_deposit = '"+txtno_dep.getText().trim()+"'");
              rs.next();
              saldo = Long.parseLong(rs.getString("saldo"));
              nama_deposit=rs.getString("nama");
              lbl_nama.setText(nama_deposit);
              lbl_saldo.setText(set_Rp(saldo));
              rs.close();
              smt.close();
              cn.close();
           }catch (Exception e){
                e.printStackTrace();
            } 
        }
    }//GEN-LAST:event_txtno_depKeyPressed

    private void cari_depActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari_depActionPerformed
        // TODO add your handling code here:
        try{
              Class.forName(JDBC_DRIVER);
              Connection cn = DriverManager.getConnection(DB_URL,USER,PASS);
              Statement smt = cn.createStatement();
              ResultSet rs = smt.executeQuery("select * from deposit where no_deposit = '"+txtno_dep.getText().trim()+"'");
              rs.next();
              saldo = Long.parseLong(rs.getString("saldo"));
              if(saldo==0)
                  JOptionPane.showMessageDialog(this,"Saldo deposit sudah habis, silahkan tambah saldo atau ganti metode pembayaran","Informasi",JOptionPane.INFORMATION_MESSAGE);
              nama_deposit=rs.getString("nama");
              lbl_nama.setText(nama_deposit);
              lbl_saldo.setText(set_Rp(saldo));
              rs.close();
              smt.close();
              cn.close();
           }catch (Exception e){
                e.printStackTrace();
            }
    }//GEN-LAST:event_cari_depActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Cari_deposit2 cd2 = new Cari_deposit2();
            cd2.tr = this;
            cd2.setLocationRelativeTo(this);
            cd2.setVisible(true);
            //cr.setResizable(false);
            itemTerpilih2();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_nmpiutangFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nmpiutangFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nmpiutangFocusLost

    private void txt_nmpiutangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nmpiutangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nmpiutangActionPerformed

    private void txt_nmpiutangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nmpiutangKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nmpiutangKeyPressed

    private void txt_nohpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nohpFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nohpFocusLost

    private void txt_nohpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nohpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nohpActionPerformed

    private void txt_nohpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nohpKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nohpKeyPressed

    private void hap_depActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hap_depActionPerformed
        // TODO add your handling code here:
        txtno_dep.setText("");
        lbl_nama.setText("");
        lbl_saldo.setText("");
    }//GEN-LAST:event_hap_depActionPerformed

    private void txt_keteranganFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_keteranganFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_keteranganFocusLost

    private void txt_keteranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_keteranganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_keteranganActionPerformed

    private void txt_keteranganKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_keteranganKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_keteranganKeyPressed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Qty;
    private javax.swing.JButton cari_dep;
    private javax.swing.JButton hap_dep;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lbl_diskon;
    private javax.swing.JLabel lbl_nama;
    private javax.swing.JLabel lbl_saldo;
    private javax.swing.JLabel lbl_subtotal;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JButton tmb_batal;
    private javax.swing.JButton tmb_cetak;
    private javax.swing.JButton tmb_hapus;
    private javax.swing.JButton tmb_tambah;
    private javax.swing.JButton tmb_tambah1;
    private javax.swing.JButton tmb_tambahdisno;
    private javax.swing.JTextField txt_diskon;
    private javax.swing.JTextField txt_diskonnota;
    private javax.swing.JTextField txt_keterangan;
    private javax.swing.JTextField txt_nmbrg;
    private javax.swing.JTextField txt_nmpiutang;
    private javax.swing.JTextField txt_nohp;
    private javax.swing.JTextField txtkd_brg;
    private javax.swing.JTextField txtno_dep;
    // End of variables declaration//GEN-END:variables
static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
static final String DB_URL = "jdbc:mysql://localhost/TB_RP";
static final String USER = "root";
static final String PASS = "";

public long G_subtotal=0;
public long G_diskon = 0;
public long G_total = 0;
public long saldo = 0;
public long tunai=0;
public long deposit=0;
public long piutang=0;
public String idBrg;
public String nama_deposit="";
public String NmBrg;
public String no_deposit="-";

    public void itemTerpilih(){
    Cari_barang cr = new Cari_barang();
    cr.tr = this;
    txtkd_brg.setText(idBrg);
    txt_nmbrg.setText(NmBrg);
    }
    public void itemTerpilih2(){
    Cari_deposit2 cd2 = new Cari_deposit2();
    cd2.tr = this;
    txtno_dep.setText(no_deposit);
    }
    public void bersihkan(){
        txtkd_brg.setText("");
        Qty.setText("");
        
        txt_nmbrg.setText("");
        txt_diskon.setText("0");
        txt_diskonnota.setText("0");
        txtkd_brg.requestFocus();        
    }
    
    public boolean cek_isitext(){
        boolean kd,qty,diskon,cek_item=cek_table();
        if(txtkd_brg.equals("")){
            JOptionPane.showMessageDialog(this,"Kode barang belum terisi!","Informasi",JOptionPane.INFORMATION_MESSAGE);
            kd = false;
        }
        else
            kd = true;
        
      if(Qty.getText().trim().equals("")==true|| cek_number(Qty.getText().trim())==false){
            JOptionPane.showMessageDialog(this,"Quantity barang belum terisi atau tidak terisi dengan benar!","Informasi",JOptionPane.INFORMATION_MESSAGE);
            qty=false;
      }
      else qty=true;
      
      if(txt_diskon.getText().trim().equals("")|| cek_number(txt_diskon.getText().trim())==false){
          JOptionPane.showMessageDialog(this,"Diskon barang belum terisi atau tidak terisi dengan benar!!","Informasi",JOptionPane.INFORMATION_MESSAGE);
            diskon=false;
      }
      else
          diskon = true;
      
      return kd && qty && diskon && cek_item;
    }
    
    public boolean cek_number(String bil){
       try{
            Double.parseDouble(bil);
       } catch (Exception e){
            return false;
               }
    return true; 
    }
    
    public void count(){
        int i = 0;
        G_subtotal=0;
        G_diskon = 0;
        G_total=0;
        
        while(i<mdl.getRowCount()){
            G_subtotal += Long.parseLong(jTable1.getModel().getValueAt(i,4).toString());
            G_diskon += Long.parseLong(jTable1.getModel().getValueAt(i,5).toString());
            i++;
        }
        G_diskon += Long.parseLong(txt_diskonnota.getText());
        G_total=G_subtotal-G_diskon;
    }
    public void set_harga(){
        lbl_subtotal.setText(set_Rp(G_subtotal));
        lbl_diskon.setText(set_Rp(G_diskon));
        lbl_total.setText(set_Rp(G_total));
    }
    
    public boolean cek_table(){
        int cek=0,i=0;
        
        while(i<mdl.getRowCount()){
            if(jTable1.getModel().getValueAt(i,0).toString().equals(txtkd_brg.getText())){
                JOptionPane.showMessageDialog(this,"Item ini sudah diinput!","Informasi",JOptionPane.INFORMATION_MESSAGE);
                cek++;
                bersihkan();
                }
        i++;
        }
        if(cek>0)
            return false;
        else
            return true;
    }
    public String Ge_transno(){
        String no_trans = "TR";
        
        Date ys = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyyMMdd");
        no_trans = no_trans.concat(s.format(ys)).concat(no_urut(s.format(ys)));
        return no_trans;
    }
    
    public String no_urut(String tgl){
        int no;
        try{
                Class.forName(JDBC_DRIVER);
                Connection cn = DriverManager.getConnection(DB_URL,USER,PASS);
                Statement smt = cn.createStatement();
                ResultSet rs = smt.executeQuery("select * from nota where No_trans like '%" + tgl +"%' order by No_trans asc");
                rs.last();
                if(rs.getRow()==0)
                    no = 1;
                else
                    no=Integer.parseInt(rs.getString("No_trans").substring(10,13))+1;
                
                if(no<10)
                    return "00".concat(String.valueOf(no));
                else if(no>=10&&no<100)
                    return "0".concat(String.valueOf(no));
                else
                    return String.valueOf(no);
            } catch (Exception e){
                e.printStackTrace();
                return null;
            } 
    }
    
    public String gene_nopi(){
        String no_trans = "PT";
        
        Date ys = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyyMMdd");
        no_trans = no_trans.concat(s.format(ys)).concat(no_urutpi(s.format(ys)));
        return no_trans;
    }
    
    public String no_urutpi(String tgl){
        int no;
        try{
                Class.forName(JDBC_DRIVER);
                Connection cn = DriverManager.getConnection(DB_URL,USER,PASS);
                Statement smt = cn.createStatement();
                ResultSet rs = smt.executeQuery("select * from piutang where No_piutang like '%" + tgl +"%' order by No_piutang asc");
                rs.last();
                if(rs.getRow()==0)
                    no = 1;
                else
                    no=Integer.parseInt(rs.getString("No_piutang").substring(10,13))+1;
                
                if(no<10)
                    return "00".concat(String.valueOf(no));
                else if(no>=10&&no<100)
                    return "0".concat(String.valueOf(no));
                else
                    return String.valueOf(no);
            } catch (Exception e){
                e.printStackTrace();
                return null;
            } 
    }
    
    public void simpan(String no_trans,String no_pi,String cr_byr){
        int i=0,col=mdl.getRowCount();long si_sal;
        if(col>0){
            Date ys = new Date();
            SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
            SimpleDateFormat s2 = new SimpleDateFormat("kk:mm:ss");
            String tgl = s.format(ys);
            String wkt = s2.format(ys);
            double temp_stok=0;
            double temp_pen=0;
            try{
              Class.forName(JDBC_DRIVER);
              Connection cn = DriverManager.getConnection(DB_URL,USER,PASS);
              Statement smt = cn.createStatement();
              while(i<col){
                    String sql = "INSERT INTO transaksi (No_trans,Tgl_trans,Wkt_trans,Kd_brg,Nm_brg,Qty,Hrg_satuan,Hrg,Diskon,modal,Jenis_pembayaran,No_deposit,No_piutang) values ('"+no_trans+"','"+tgl+"','"+wkt+"','"+jTable1.getModel().getValueAt(i,0).toString()+"','"+jTable1.getModel().getValueAt(i,1).toString()+"','"+jTable1.getModel().getValueAt(i,2).toString()+"','"+jTable1.getModel().getValueAt(i,3).toString()+"','"+jTable1.getModel().getValueAt(i,4).toString()+"','"+jTable1.getModel().getValueAt(i,5).toString()+"','"+Double.parseDouble(jTable1.getModel().getValueAt(i,2).toString())*getmodal(jTable1.getModel().getValueAt(i,0).toString())+"','"+cr_byr+"','"+no_deposit+"','"+no_pi+"')";
                    smt.executeUpdate(sql);
                    ResultSet rs = smt.executeQuery("select * from barang where Kd_brg = '" + jTable1.getModel().getValueAt(i,0) +"'");
                    rs.next();
                    temp_stok=Double.parseDouble(rs.getString("Stok"))- Double.parseDouble(jTable1.getModel().getValueAt(i,2).toString());
                    temp_pen= Double.parseDouble(rs.getString("Penjualan"))+ Double.parseDouble(jTable1.getModel().getValueAt(i,2).toString());;
                    smt.executeUpdate("UPDATE barang SET Stok = '"+temp_stok+"',Penjualan = '"+temp_pen+"' where Kd_brg = '"+jTable1.getModel().getValueAt(i,0).toString()+"'");
                    i++;
              }
              
              if(cr_byr.equals("Deposit")){
                  deposit=G_total;
                  saldo = saldo-G_total;
                  smt.executeUpdate("UPDATE deposit set saldo = '"+saldo+"' where no_deposit = '"+no_deposit+"'");
              }
              else if(cr_byr.equals("Deposit dan Tunai")){
                  deposit=saldo;
                  tunai=G_total-deposit;
                  saldo=0;
                  smt.executeUpdate("UPDATE deposit set saldo = '"+saldo+"' where no_deposit = '"+no_deposit+"'");
              }
              else if(cr_byr.equals("Piutang")){
                  piutang=G_total;
                  smt.executeUpdate("INSERT INTO piutang (No_piutang,Nama,No_hp,Tgl_trans,Tgl_jatuhtempo,Total,Sisa_piutang,Keterangan)" + " values ('"+no_pi+"','"+txt_nmpiutang.getText().trim()+"','"+txt_nohp.getText().trim()+"','"+tgl+"','"+s.format(jDateChooser1.getDate())+"','"+piutang+"','"+piutang+"','"+txt_keterangan.getText().trim()+"')");
              }
              else if(cr_byr.equals("Deposit dan Piutang")){
                  deposit = saldo;
                  piutang = G_total-saldo;
                  smt.executeUpdate("INSERT INTO piutang (No_piutang,Nama,No_hp,Tgl_trans,Tgl_jatuhtempo,Total,Sisa_piutang,Keterangan)" + " values ('"+no_pi+"','"+txt_nmpiutang.getText().trim()+"','"+txt_nohp.getText().trim()+"','"+tgl+"','"+s.format(jDateChooser1.getDate())+"','"+piutang+"','"+piutang+"','"+txt_keterangan.getText().trim()+"')");
                  saldo=0;
                  smt.executeUpdate("UPDATE deposit set saldo = '"+saldo+"' where no_deposit = '"+no_deposit+"'");
              }
              else{
                  tunai=G_total;
              }
              smt.executeUpdate("INSERT INTO nota (No_trans,Tgl_trans,Wkt_trans,Sub_total,Diskon,Total,Jenis_pembayaran,No_deposit,No_piutang,cash,deposit,piutang)" + " values ('"+no_trans+"','"+tgl+"','"+wkt+"','"+G_subtotal+"','"+G_diskon+"','"+G_total+"','"+cr_byr+"','"+no_deposit+"','"+no_pi+"','"+tunai+"','"+deposit+"','"+piutang+"')");
              smt.close();
              cn.close();
            } catch (Exception e){
                e.printStackTrace();
                }
        }
        else
            JOptionPane.showMessageDialog(this,"Item belum diinput","Informasi",JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void bersihkan_Table(){
        int j_brs = mdl.getRowCount()-1;
        int i = j_brs;
        while(i>=0){
            mdl.removeRow(i);
            i=i-1;
        }
        G_subtotal = 0;
        G_diskon = 0;
        G_total = 0;
        set_harga();
        
    }
    
    public void cetak_nota(String no_tr,String no_pi,String cr_byr){
        SimpleDateFormat dt = new SimpleDateFormat("dd/MM/yyyy");
        String tgl_jth="",sisal="";
        if(jComboBox3.getSelectedItem().equals("Deposit"))
            sisal=set_Rp(saldo);
        else if(jComboBox3.getSelectedItem().equals("Deposit dan Piutang")){
            tgl_jth=dt.format(jDateChooser1.getDate());
            sisal=set_Rp(saldo);
        }
        else if(jComboBox3.getSelectedItem().equals("Deposit dan Tunai"))
            sisal=set_Rp(saldo);
        else if(jComboBox3.getSelectedItem().equals("Piutang")){
            tgl_jth=dt.format(jDateChooser1.getDate());
        }
        try{
            HashMap parameter = new HashMap();
            Class.forName("com.mysql.jdbc.Driver");
            Connection cn = DriverManager.getConnection("jdbc:mysql:"+"///tb_rp","root","" );
            Statement smt = cn.createStatement();
            ResultSet rs = smt.executeQuery("select * from nota where No_trans = '"+no_tr+"'");
            rs.next();
            if(rs.getRow()>0){
                JasperDesign jdesign = JRXmlLoader.load("src/nota.jrxml");
                parameter.put("No_trans",no_tr);
                parameter.put("Grand_total",set_Rp(G_subtotal));
                parameter.put("Diskon",set_Rp(G_diskon));
                parameter.put("Total",set_Rp(G_total));
                parameter.put("cr_byr","Transaksi "+cr_byr);
                parameter.put("tot_cash",set_Rp(tunai));
                parameter.put("tot_dep",set_Rp(deposit));
                parameter.put("tot_pi",set_Rp(piutang));
                parameter.put("jth_tempo",tgl_jth);
                parameter.put("sisa_saldo",sisal);
                String query = "select* from transaksi where no_trans = '"+no_tr+"'";
                JRDesignQuery updateQuery = new JRDesignQuery();
                updateQuery.setText(query);
                jdesign.setQuery(updateQuery);
                JasperReport jreport = JasperCompileManager.compileReport(jdesign);
                JasperPrint jprint = JasperFillManager.fillReport(jreport,parameter,cn);
                JasperViewer.viewReport(jprint,false);
            }
            else
                JOptionPane.showMessageDialog(null,"Transaksi tidak ditemukan", "Informasi",JOptionPane.ERROR_MESSAGE);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Data tidak dapat dicetak! \n"+e.getMessage(), "Cetak Data",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public String set_Rp(Long bil){
        DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
        DecimalFormatSymbols formatRp = new DecimalFormatSymbols();

        formatRp.setCurrencySymbol("Rp ");
        formatRp.setMonetaryDecimalSeparator(',');
        formatRp.setGroupingSeparator('.');

        kursIndonesia.setDecimalFormatSymbols(formatRp);
        
        return kursIndonesia.format(bil);
    }
    
    public static boolean isNumeric(String strNum) {
        if (strNum == null) {
            return false;
        }
        try {
            double d = Double.parseDouble(strNum);
        } catch (NumberFormatException nfe) {
            return false;
            }
        return true;
    }

    private long getmodal(String kd) {
        long modal=0;
        try{
            Class.forName(JDBC_DRIVER);
            Connection cn = DriverManager.getConnection(DB_URL,USER,PASS);
            Statement smt = cn.createStatement();
            ResultSet rs = smt.executeQuery("select * from barang where Kd_brg ='"+kd+"'");
            rs.next();
            modal=Long.parseLong(rs.getString("modal"));
            rs.close();
            smt.close();
            cn.close();
        }catch (Exception e){
                e.printStackTrace();
            }
        return modal;
    }
}
